// Code generated by honey. DO NOT EDIT.

package sdk

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"sync"
	"time"
)

var _ = fmt.Sprintf
var _ = io.Discard
var _ = strings.NewReader
var _ = sync.Mutex{}

type serviceEntry struct {
	Method     string
	Path       string
	Params     []string
	SSE        bool
	WS         bool
	Invalidate []string
}

var invalidationMap = map[string]map[string]serviceEntry{
	"batch": {
		"download.csv":  {Method: "GET", Path: "/v1/projects/{project_id}/batches/{batch_id}/download/csv", Params: []string{"project_id", "batch_id"}, SSE: false, WS: false, Invalidate: nil},
		"download.json": {Method: "GET", Path: "/v1/projects/{project_id}/batches/{batch_id}/download/json", Params: []string{"project_id", "batch_id"}, SSE: false, WS: false, Invalidate: nil},
		"download.xlsx": {Method: "GET", Path: "/v1/projects/{project_id}/batches/{batch_id}/download/xlsx", Params: []string{"project_id", "batch_id"}, SSE: false, WS: false, Invalidate: nil},
		"get":           {Method: "GET", Path: "/v1/projects/{project_id}/batches/{batch_id}", Params: []string{"project_id", "batch_id"}, SSE: false, WS: false, Invalidate: nil},
		"list":          {Method: "GET", Path: "/v1/projects/{project_id}/batches", Params: []string{"project_id"}, SSE: false, WS: false, Invalidate: nil},
	},
	"column": {
		"add":      {Method: "POST", Path: "/v1/projects/{project_id}/tables/{table_id}/columns", Params: []string{"project_id", "table_id"}, SSE: false, WS: false, Invalidate: nil},
		"distinct": {Method: "GET", Path: "/v1/projects/{project_id}/tables/{table_id}/columns/{col_id}/distinct", Params: []string{"project_id", "table_id", "col_id"}, SSE: false, WS: false, Invalidate: nil},
		"remove":   {Method: "DELETE", Path: "/v1/projects/{project_id}/tables/{table_id}/columns/{col_id}", Params: []string{"project_id", "table_id", "col_id"}, SSE: false, WS: false, Invalidate: nil},
		"reorder":  {Method: "PUT", Path: "/v1/projects/{project_id}/tables/{table_id}/columns/order", Params: []string{"project_id", "table_id"}, SSE: false, WS: false, Invalidate: nil},
		"update":   {Method: "PATCH", Path: "/v1/projects/{project_id}/tables/{table_id}/columns/{col_id}", Params: []string{"project_id", "table_id", "col_id"}, SSE: false, WS: false, Invalidate: nil},
	},
	"export": {
		"get": {Method: "GET", Path: "/v1/projects/{project_id}/exports/{export_id}", Params: []string{"project_id", "export_id"}, SSE: false, WS: false, Invalidate: nil},
	},
	"extract": {
		"once":         {Method: "POST", Path: "/v1/projects/{project_id}/extract", Params: []string{"project_id"}, SSE: false, WS: false, Invalidate: nil},
		"stream":       {Method: "POST", Path: "/v1/projects/{project_id}/extract-stream", Params: []string{"project_id"}, SSE: false, WS: false, Invalidate: nil},
		"table.once":   {Method: "POST", Path: "/v1/projects/{project_id}/tables/{table_id}/extract", Params: []string{"project_id", "table_id"}, SSE: false, WS: false, Invalidate: nil},
		"table.stream": {Method: "POST", Path: "/v1/projects/{project_id}/tables/{table_id}/extract-stream", Params: []string{"project_id", "table_id"}, SSE: false, WS: false, Invalidate: nil},
	},
	"row": {
		"aggregate": {Method: "GET", Path: "/v1/projects/{project_id}/tables/{table_id}/rows/aggregate", Params: []string{"project_id", "table_id"}, SSE: false, WS: false, Invalidate: nil},
		"bulk":      {Method: "POST", Path: "/v1/projects/{project_id}/tables/{table_id}/rows/bulk", Params: []string{"project_id", "table_id"}, SSE: false, WS: false, Invalidate: nil},
		"create":    {Method: "POST", Path: "/v1/projects/{project_id}/tables/{table_id}/rows", Params: []string{"project_id", "table_id"}, SSE: false, WS: false, Invalidate: nil},
		"delete":    {Method: "DELETE", Path: "/v1/projects/{project_id}/tables/{table_id}/rows/{row_id}", Params: []string{"project_id", "table_id", "row_id"}, SSE: false, WS: false, Invalidate: nil},
		"get":       {Method: "GET", Path: "/v1/projects/{project_id}/tables/{table_id}/rows/{row_id}", Params: []string{"project_id", "table_id", "row_id"}, SSE: false, WS: false, Invalidate: nil},
		"list":      {Method: "GET", Path: "/v1/projects/{project_id}/tables/{table_id}/rows", Params: []string{"project_id", "table_id"}, SSE: false, WS: false, Invalidate: nil},
		"update":    {Method: "PATCH", Path: "/v1/projects/{project_id}/tables/{table_id}/rows/{row_id}", Params: []string{"project_id", "table_id", "row_id"}, SSE: false, WS: false, Invalidate: nil},
	},
	"suggest": {
		"schema": {Method: "POST", Path: "/v1/projects/{project_id}/suggest-schema", Params: []string{"project_id"}, SSE: false, WS: false, Invalidate: nil},
	},
	"table": {
		"create":    {Method: "POST", Path: "/v1/projects/{project_id}/tables", Params: []string{"project_id"}, SSE: false, WS: false, Invalidate: nil},
		"delete":    {Method: "DELETE", Path: "/v1/projects/{project_id}/tables/{table_id}", Params: []string{"project_id", "table_id"}, SSE: false, WS: false, Invalidate: nil},
		"duplicate": {Method: "POST", Path: "/v1/projects/{project_id}/tables/{table_id}/duplicate", Params: []string{"project_id", "table_id"}, SSE: false, WS: false, Invalidate: nil},
		"export":    {Method: "GET", Path: "/v1/projects/{project_id}/tables/{table_id}/export", Params: []string{"project_id", "table_id"}, SSE: false, WS: false, Invalidate: nil},
		"get":       {Method: "GET", Path: "/v1/projects/{project_id}/tables/{table_id}", Params: []string{"project_id", "table_id"}, SSE: false, WS: false, Invalidate: nil},
		"list":      {Method: "GET", Path: "/v1/projects/{project_id}/tables", Params: []string{"project_id"}, SSE: false, WS: false, Invalidate: nil},
		"restore":   {Method: "POST", Path: "/v1/projects/{project_id}/tables/{table_id}/restore", Params: []string{"project_id", "table_id"}, SSE: false, WS: false, Invalidate: nil},
		"update":    {Method: "PATCH", Path: "/v1/projects/{project_id}/tables/{table_id}", Params: []string{"project_id", "table_id"}, SSE: false, WS: false, Invalidate: nil},
	},
	"tableTemplate": {
		"create":      {Method: "POST", Path: "/v1/table-templates", Params: nil, SSE: false, WS: false, Invalidate: nil},
		"delete":      {Method: "DELETE", Path: "/v1/table-templates/{template_id}", Params: []string{"template_id"}, SSE: false, WS: false, Invalidate: nil},
		"listMine":    {Method: "GET", Path: "/v1/table-templates/mine", Params: nil, SSE: false, WS: false, Invalidate: nil},
		"projectGet":  {Method: "GET", Path: "/v1/projects/{project_id}/table-templates/{template_id}", Params: []string{"project_id", "template_id"}, SSE: false, WS: false, Invalidate: nil},
		"projectList": {Method: "GET", Path: "/v1/projects/{project_id}/table-templates", Params: []string{"project_id"}, SSE: false, WS: false, Invalidate: nil},
		"update":      {Method: "PATCH", Path: "/v1/table-templates/{template_id}", Params: []string{"template_id"}, SSE: false, WS: false, Invalidate: nil},
		"use":         {Method: "POST", Path: "/v1/projects/{project_id}/table-templates/{template_id}/use", Params: []string{"project_id", "template_id"}, SSE: false, WS: false, Invalidate: nil},
	},
	"webhook": {
		"create":       {Method: "POST", Path: "/v1/organizations/{organization_id}/webhooks", Params: []string{"organization_id"}, SSE: false, WS: false, Invalidate: nil},
		"delete":       {Method: "DELETE", Path: "/v1/organizations/{organization_id}/webhooks/{id}", Params: []string{"organization_id", "id"}, SSE: false, WS: false, Invalidate: nil},
		"deliveries":   {Method: "GET", Path: "/v1/organizations/{organization_id}/webhooks/{id}/deliveries", Params: []string{"organization_id", "id"}, SSE: false, WS: false, Invalidate: nil},
		"get":          {Method: "GET", Path: "/v1/organizations/{organization_id}/webhooks/{id}", Params: []string{"organization_id", "id"}, SSE: false, WS: false, Invalidate: nil},
		"list":         {Method: "GET", Path: "/v1/organizations/{organization_id}/webhooks", Params: []string{"organization_id"}, SSE: false, WS: false, Invalidate: nil},
		"rotateSecret": {Method: "POST", Path: "/v1/organizations/{organization_id}/webhooks/{id}/rotate-secret", Params: []string{"organization_id", "id"}, SSE: false, WS: false, Invalidate: nil},
		"test":         {Method: "POST", Path: "/v1/organizations/{organization_id}/webhooks/{id}/test", Params: []string{"organization_id", "id"}, SSE: false, WS: false, Invalidate: nil},
		"update":       {Method: "PATCH", Path: "/v1/organizations/{organization_id}/webhooks/{id}", Params: []string{"organization_id", "id"}, SSE: false, WS: false, Invalidate: nil},
	},
}

// Client is the generated SDK client.
type Client struct {
	cfg           Config
	stale         *StaleTracker
	Batch         *BatchResource
	Column        *ColumnResource
	Export        *ExportResource
	Extract       *ExtractResource
	Row           *RowResource
	Suggest       *SuggestResource
	Table         *TableResource
	TableTemplate *TableTemplateResource
	Webhook       *WebhookResource
}

// NewClient creates a new SDK client. BaseURL must be non-empty.
func NewClient(cfg Config) *Client {
	if cfg.BaseURL == "" {
		panic("honey sdk: Config.BaseURL must not be empty")
	}
	if cfg.HTTPClient == nil {
		cfg.HTTPClient = &http.Client{Timeout: 30 * time.Second}
	}
	if cfg.AuthHeaderName == "" {
		cfg.AuthHeaderName = "Authorization"
	}
	if cfg.AuthHeaderPrefix == "" {
		cfg.AuthHeaderPrefix = "ApiKey "
	}
	c := &Client{cfg: cfg}
	c.stale = NewStaleTracker(cfg.Invalidation)
	c.Batch = newBatchResource(c)
	c.Column = newColumnResource(c)
	c.Export = newExportResource(c)
	c.Extract = newExtractResource(c)
	c.Row = newRowResource(c)
	c.Suggest = newSuggestResource(c)
	c.Table = newTableResource(c)
	c.TableTemplate = newTableTemplateResource(c)
	c.Webhook = newWebhookResource(c)
	return c
}

// IsStale reports whether (method, path) currently sits inside an active stale window.
func (c *Client) IsStale(method, path string) bool {
	if c.stale == nil {
		return false
	}
	return c.stale.IsStale(method, path)
}

type BatchResource struct {
	client   *Client
	Download *BatchDownloadResource
}

func newBatchResource(c *Client) *BatchResource {
	r := &BatchResource{client: c}
	r.Download = newBatchDownloadResource(c)
	return r
}

// Get — Get batch
func (b *BatchResource) Get(ctx context.Context, project_id string, batch_id string, opts *BatchGetOpts) (*GetProjectsBatcheResponse200, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, b.client.cfg, "GET", "/v1/projects/"+url.PathEscape(project_id)+"/batches/"+url.PathEscape(batch_id), q, nil, nil, "", callHeaders, "GET /v1/projects/{project_id}/batches/{batch_id}", nil)
	if err != nil {
		return nil, err
	}
	var out GetProjectsBatcheResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// List — List batches
func (b *BatchResource) List(ctx context.Context, project_id string, opts *BatchListOpts) (*ListProjectsBatchesResponse200, error) {
	q := url.Values{}
	if opts != nil && opts.Cursor != nil {
		q.Set("cursor", *opts.Cursor)
	}
	if opts != nil && opts.Filter != nil {
		q.Set("filter", *opts.Filter)
	}
	if opts != nil && opts.Lang != nil {
		q.Set("lang", *opts.Lang)
	}
	if opts != nil && opts.Limit != nil {
		q.Set("limit", strconv.FormatInt(*opts.Limit, 10))
	}
	if opts != nil && opts.Order != nil {
		q.Set("order", *opts.Order)
	}
	if opts != nil && opts.Page != nil {
		q.Set("page", strconv.FormatInt(*opts.Page, 10))
	}
	if opts != nil && opts.Q != nil {
		q.Set("q", *opts.Q)
	}
	if opts != nil && opts.Select != nil {
		q.Set("select", *opts.Select)
	}
	if opts != nil && opts.Status != nil {
		q.Set("status", string(*opts.Status))
	}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, b.client.cfg, "GET", "/v1/projects/"+url.PathEscape(project_id)+"/batches", q, nil, nil, "", callHeaders, "GET /v1/projects/{project_id}/batches", nil)
	if err != nil {
		return nil, err
	}
	var out ListProjectsBatchesResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

type BatchDownloadResource struct {
	client *Client
}

func newBatchDownloadResource(c *Client) *BatchDownloadResource {
	r := &BatchDownloadResource{client: c}
	return r
}

// Csv — Download batch CSV
func (d *BatchDownloadResource) Csv(ctx context.Context, project_id string, batch_id string, opts *BatchDownloadCsvOpts) (*json.RawMessage, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, d.client.cfg, "GET", "/v1/projects/"+url.PathEscape(project_id)+"/batches/"+url.PathEscape(batch_id)+"/download/csv", q, nil, nil, "", callHeaders, "GET /v1/projects/{project_id}/batches/{batch_id}/download/csv", nil)
	if err != nil {
		return nil, err
	}
	var out json.RawMessage
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Json — Download batch JSON
func (d *BatchDownloadResource) Json(ctx context.Context, project_id string, batch_id string, opts *BatchDownloadJsonOpts) (*json.RawMessage, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, d.client.cfg, "GET", "/v1/projects/"+url.PathEscape(project_id)+"/batches/"+url.PathEscape(batch_id)+"/download/json", q, nil, nil, "", callHeaders, "GET /v1/projects/{project_id}/batches/{batch_id}/download/json", nil)
	if err != nil {
		return nil, err
	}
	var out json.RawMessage
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Xlsx — Download batch XLSX
func (d *BatchDownloadResource) Xlsx(ctx context.Context, project_id string, batch_id string, opts *BatchDownloadXlsxOpts) (*json.RawMessage, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, d.client.cfg, "GET", "/v1/projects/"+url.PathEscape(project_id)+"/batches/"+url.PathEscape(batch_id)+"/download/xlsx", q, nil, nil, "", callHeaders, "GET /v1/projects/{project_id}/batches/{batch_id}/download/xlsx", nil)
	if err != nil {
		return nil, err
	}
	var out json.RawMessage
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

type ColumnResource struct {
	client *Client
}

func newColumnResource(c *Client) *ColumnResource {
	r := &ColumnResource{client: c}
	return r
}

// Add — Add column
func (c *ColumnResource) Add(ctx context.Context, project_id string, table_id string, body CreateProjectsTablesColumnRequest, opts *ColumnAddOpts) (*CreateProjectsTableTemplatesUseResponse201, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, c.client.cfg, "POST", "/v1/projects/"+url.PathEscape(project_id)+"/tables/"+url.PathEscape(table_id)+"/columns", q, body, nil, "", callHeaders, "POST /v1/projects/{project_id}/tables/{table_id}/columns", nil)
	if err != nil {
		return nil, err
	}
	var out CreateProjectsTableTemplatesUseResponse201
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Distinct — Get distinct column values
func (c *ColumnResource) Distinct(ctx context.Context, project_id string, table_id string, col_id string, opts *ColumnDistinctOpts) (*ListProjectsTablesColumnsDistinctResponse200, error) {
	q := url.Values{}
	if opts != nil && opts.Limit != nil {
		q.Set("limit", strconv.FormatInt(*opts.Limit, 10))
	}
	if opts != nil && opts.Q != nil {
		q.Set("q", *opts.Q)
	}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, c.client.cfg, "GET", "/v1/projects/"+url.PathEscape(project_id)+"/tables/"+url.PathEscape(table_id)+"/columns/"+url.PathEscape(col_id)+"/distinct", q, nil, nil, "", callHeaders, "GET /v1/projects/{project_id}/tables/{table_id}/columns/{col_id}/distinct", nil)
	if err != nil {
		return nil, err
	}
	var out ListProjectsTablesColumnsDistinctResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Remove — Remove column
func (c *ColumnResource) Remove(ctx context.Context, project_id string, table_id string, col_id string, opts *ColumnRemoveOpts) (*CreateProjectsTableTemplatesUseResponse201, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, c.client.cfg, "DELETE", "/v1/projects/"+url.PathEscape(project_id)+"/tables/"+url.PathEscape(table_id)+"/columns/"+url.PathEscape(col_id), q, nil, nil, "", callHeaders, "DELETE /v1/projects/{project_id}/tables/{table_id}/columns/{col_id}", nil)
	if err != nil {
		return nil, err
	}
	var out CreateProjectsTableTemplatesUseResponse201
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Reorder — Reorder columns
func (c *ColumnResource) Reorder(ctx context.Context, project_id string, table_id string, body ReplaceProjectsTablesColumnRequest, opts *ColumnReorderOpts) (*CreateProjectsTableTemplatesUseResponse201, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, c.client.cfg, "PUT", "/v1/projects/"+url.PathEscape(project_id)+"/tables/"+url.PathEscape(table_id)+"/columns/order", q, body, nil, "", callHeaders, "PUT /v1/projects/{project_id}/tables/{table_id}/columns/order", nil)
	if err != nil {
		return nil, err
	}
	var out CreateProjectsTableTemplatesUseResponse201
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Update — Update column
func (c *ColumnResource) Update(ctx context.Context, project_id string, table_id string, col_id string, body UpdateProjectsTablesColumnRequest, opts *ColumnUpdateOpts) (*CreateProjectsTableTemplatesUseResponse201, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, c.client.cfg, "PATCH", "/v1/projects/"+url.PathEscape(project_id)+"/tables/"+url.PathEscape(table_id)+"/columns/"+url.PathEscape(col_id), q, body, nil, "", callHeaders, "PATCH /v1/projects/{project_id}/tables/{table_id}/columns/{col_id}", nil)
	if err != nil {
		return nil, err
	}
	var out CreateProjectsTableTemplatesUseResponse201
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

type ExportResource struct {
	client *Client
}

func newExportResource(c *Client) *ExportResource {
	r := &ExportResource{client: c}
	return r
}

// Get — Get export status
func (e *ExportResource) Get(ctx context.Context, project_id string, export_id string, opts *ExportGetOpts) (*GetProjectsExportResponse200, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, e.client.cfg, "GET", "/v1/projects/"+url.PathEscape(project_id)+"/exports/"+url.PathEscape(export_id), q, nil, nil, "", callHeaders, "GET /v1/projects/{project_id}/exports/{export_id}", nil)
	if err != nil {
		return nil, err
	}
	var out GetProjectsExportResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

type ExtractResource struct {
	client *Client
	Table  *ExtractTableResource
}

func newExtractResource(c *Client) *ExtractResource {
	r := &ExtractResource{client: c}
	r.Table = newExtractTableResource(c)
	return r
}

// Once — Extract data from text or file (JSON response)
func (e *ExtractResource) Once(ctx context.Context, project_id string, opts *ExtractOnceOpts) (*CreateProjectsExtractResponse200, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, e.client.cfg, "POST", "/v1/projects/"+url.PathEscape(project_id)+"/extract", q, nil, nil, "", callHeaders, "POST /v1/projects/{project_id}/extract", nil)
	if err != nil {
		return nil, err
	}
	var out CreateProjectsExtractResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Stream — Extract data from text or file (SSE stream)
func (e *ExtractResource) Stream(ctx context.Context, project_id string, opts *ExtractStreamOpts) (*json.RawMessage, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, e.client.cfg, "POST", "/v1/projects/"+url.PathEscape(project_id)+"/extract-stream", q, nil, nil, "", callHeaders, "POST /v1/projects/{project_id}/extract-stream", nil)
	if err != nil {
		return nil, err
	}
	var out json.RawMessage
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

type ExtractTableResource struct {
	client *Client
}

func newExtractTableResource(c *Client) *ExtractTableResource {
	r := &ExtractTableResource{client: c}
	return r
}

// Once — Extract into table (JSON response)
func (t *ExtractTableResource) Once(ctx context.Context, project_id string, table_id string, opts *ExtractTableOnceOpts) (*CreateProjectsExtractResponse200, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, t.client.cfg, "POST", "/v1/projects/"+url.PathEscape(project_id)+"/tables/"+url.PathEscape(table_id)+"/extract", q, nil, nil, "", callHeaders, "POST /v1/projects/{project_id}/tables/{table_id}/extract", nil)
	if err != nil {
		return nil, err
	}
	var out CreateProjectsExtractResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Stream — Extract into table (SSE stream)
func (t *ExtractTableResource) Stream(ctx context.Context, project_id string, table_id string, opts *ExtractTableStreamOpts) (*json.RawMessage, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, t.client.cfg, "POST", "/v1/projects/"+url.PathEscape(project_id)+"/tables/"+url.PathEscape(table_id)+"/extract-stream", q, nil, nil, "", callHeaders, "POST /v1/projects/{project_id}/tables/{table_id}/extract-stream", nil)
	if err != nil {
		return nil, err
	}
	var out json.RawMessage
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

type RowResource struct {
	client *Client
}

func newRowResource(c *Client) *RowResource {
	r := &RowResource{client: c}
	return r
}

// Aggregate — Aggregate column values
func (r *RowResource) Aggregate(ctx context.Context, project_id string, table_id string, opts *RowAggregateOpts) (*ListProjectsTablesRowsResponse200F7f633, error) {
	q := url.Values{}
	if opts != nil {
		q.Set("aggs", opts.Aggs)
	}
	if opts != nil && opts.Filter != nil {
		q.Set("filter", *opts.Filter)
	}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, r.client.cfg, "GET", "/v1/projects/"+url.PathEscape(project_id)+"/tables/"+url.PathEscape(table_id)+"/rows/aggregate", q, nil, nil, "", callHeaders, "GET /v1/projects/{project_id}/tables/{table_id}/rows/aggregate", nil)
	if err != nil {
		return nil, err
	}
	var out ListProjectsTablesRowsResponse200F7f633
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Bulk — Bulk create/update/delete rows
func (r *RowResource) Bulk(ctx context.Context, project_id string, table_id string, body CreateProjectsTablesRowRequestDbbb57, opts *RowBulkOpts) (*CreateProjectsTablesRowResponse200, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, r.client.cfg, "POST", "/v1/projects/"+url.PathEscape(project_id)+"/tables/"+url.PathEscape(table_id)+"/rows/bulk", q, body, nil, "", callHeaders, "POST /v1/projects/{project_id}/tables/{table_id}/rows/bulk", nil)
	if err != nil {
		return nil, err
	}
	var out CreateProjectsTablesRowResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Create — Create row
func (r *RowResource) Create(ctx context.Context, project_id string, table_id string, body CreateProjectsTablesRowRequest, opts *RowCreateOpts) (*CreateProjectsTablesRowRequest, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, r.client.cfg, "POST", "/v1/projects/"+url.PathEscape(project_id)+"/tables/"+url.PathEscape(table_id)+"/rows", q, body, nil, "", callHeaders, "POST /v1/projects/{project_id}/tables/{table_id}/rows", nil)
	if err != nil {
		return nil, err
	}
	var out CreateProjectsTablesRowRequest
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Delete — Delete row
func (r *RowResource) Delete(ctx context.Context, project_id string, table_id string, row_id string, opts *RowDeleteOpts) (*DeleteOrganizationsWebhookResponse200, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, r.client.cfg, "DELETE", "/v1/projects/"+url.PathEscape(project_id)+"/tables/"+url.PathEscape(table_id)+"/rows/"+url.PathEscape(row_id), q, nil, nil, "", callHeaders, "DELETE /v1/projects/{project_id}/tables/{table_id}/rows/{row_id}", nil)
	if err != nil {
		return nil, err
	}
	var out DeleteOrganizationsWebhookResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Get — Get row
func (r *RowResource) Get(ctx context.Context, project_id string, table_id string, row_id string, opts *RowGetOpts) (*CreateProjectsTablesRowRequest, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, r.client.cfg, "GET", "/v1/projects/"+url.PathEscape(project_id)+"/tables/"+url.PathEscape(table_id)+"/rows/"+url.PathEscape(row_id), q, nil, nil, "", callHeaders, "GET /v1/projects/{project_id}/tables/{table_id}/rows/{row_id}", nil)
	if err != nil {
		return nil, err
	}
	var out CreateProjectsTablesRowRequest
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// List — List rows
func (r *RowResource) List(ctx context.Context, project_id string, table_id string, opts *RowListOpts) (*ListProjectsTablesRowsResponse200, error) {
	q := url.Values{}
	if opts != nil && opts.Cursor != nil {
		q.Set("cursor", *opts.Cursor)
	}
	if opts != nil && opts.Filter != nil {
		q.Set("filter", *opts.Filter)
	}
	if opts != nil && opts.Limit != nil {
		q.Set("limit", strconv.FormatInt(*opts.Limit, 10))
	}
	if opts != nil && opts.Order != nil {
		q.Set("order", *opts.Order)
	}
	if opts != nil && opts.Page != nil {
		q.Set("page", strconv.FormatInt(*opts.Page, 10))
	}
	if opts != nil && opts.Q != nil {
		q.Set("q", *opts.Q)
	}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, r.client.cfg, "GET", "/v1/projects/"+url.PathEscape(project_id)+"/tables/"+url.PathEscape(table_id)+"/rows", q, nil, nil, "", callHeaders, "GET /v1/projects/{project_id}/tables/{table_id}/rows", nil)
	if err != nil {
		return nil, err
	}
	var out ListProjectsTablesRowsResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Update — Update row
func (r *RowResource) Update(ctx context.Context, project_id string, table_id string, row_id string, body CreateProjectsTablesRowRequest, opts *RowUpdateOpts) (*CreateProjectsTablesRowRequest, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, r.client.cfg, "PATCH", "/v1/projects/"+url.PathEscape(project_id)+"/tables/"+url.PathEscape(table_id)+"/rows/"+url.PathEscape(row_id), q, body, nil, "", callHeaders, "PATCH /v1/projects/{project_id}/tables/{table_id}/rows/{row_id}", nil)
	if err != nil {
		return nil, err
	}
	var out CreateProjectsTablesRowRequest
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

type SuggestResource struct {
	client *Client
}

func newSuggestResource(c *Client) *SuggestResource {
	r := &SuggestResource{client: c}
	return r
}

// Schema — Suggest schema from text or file (multipart)
func (s *SuggestResource) Schema(ctx context.Context, project_id string, opts *SuggestSchemaOpts) (*CreateProjectsSuggestSchemaResponse200, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, s.client.cfg, "POST", "/v1/projects/"+url.PathEscape(project_id)+"/suggest-schema", q, nil, nil, "", callHeaders, "POST /v1/projects/{project_id}/suggest-schema", nil)
	if err != nil {
		return nil, err
	}
	var out CreateProjectsSuggestSchemaResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

type TableResource struct {
	client *Client
}

func newTableResource(c *Client) *TableResource {
	r := &TableResource{client: c}
	return r
}

// Create — Create table
func (t *TableResource) Create(ctx context.Context, project_id string, body CreateProjectsTableRequest, opts *TableCreateOpts) (*CreateProjectsTableTemplatesUseResponse201, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, t.client.cfg, "POST", "/v1/projects/"+url.PathEscape(project_id)+"/tables", q, body, nil, "", callHeaders, "POST /v1/projects/{project_id}/tables", nil)
	if err != nil {
		return nil, err
	}
	var out CreateProjectsTableTemplatesUseResponse201
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Delete — Delete table (soft, 72h grace)
func (t *TableResource) Delete(ctx context.Context, project_id string, table_id string, opts *TableDeleteOpts) (*DeleteOrganizationsWebhookResponse200, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, t.client.cfg, "DELETE", "/v1/projects/"+url.PathEscape(project_id)+"/tables/"+url.PathEscape(table_id), q, nil, nil, "", callHeaders, "DELETE /v1/projects/{project_id}/tables/{table_id}", nil)
	if err != nil {
		return nil, err
	}
	var out DeleteOrganizationsWebhookResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Duplicate — Duplicate table structure
func (t *TableResource) Duplicate(ctx context.Context, project_id string, table_id string, body CreateProjectsTablesDuplicateRequest, opts *TableDuplicateOpts) (*CreateProjectsTableTemplatesUseResponse201, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, t.client.cfg, "POST", "/v1/projects/"+url.PathEscape(project_id)+"/tables/"+url.PathEscape(table_id)+"/duplicate", q, body, nil, "", callHeaders, "POST /v1/projects/{project_id}/tables/{table_id}/duplicate", nil)
	if err != nil {
		return nil, err
	}
	var out CreateProjectsTableTemplatesUseResponse201
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Export — Export table rows
func (t *TableResource) Export(ctx context.Context, project_id string, table_id string, opts *TableExportOpts) (*GetProjectsExportResponse200, error) {
	q := url.Values{}
	if opts != nil && opts.Filter != nil {
		q.Set("filter", *opts.Filter)
	}
	if opts != nil {
		q.Set("format", string(opts.Format))
	}
	if opts != nil && opts.Order != nil {
		q.Set("order", *opts.Order)
	}
	if opts != nil && opts.Schema != nil {
		q.Set("schema", string(*opts.Schema))
	}
	if opts != nil && opts.Search != nil {
		q.Set("search", *opts.Search)
	}
	if opts != nil && opts.Since != nil {
		q.Set("since", *opts.Since)
	}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, t.client.cfg, "GET", "/v1/projects/"+url.PathEscape(project_id)+"/tables/"+url.PathEscape(table_id)+"/export", q, nil, nil, "", callHeaders, "GET /v1/projects/{project_id}/tables/{table_id}/export", nil)
	if err != nil {
		return nil, err
	}
	var out GetProjectsExportResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Get — Get table
func (t *TableResource) Get(ctx context.Context, project_id string, table_id string, opts *TableGetOpts) (*CreateProjectsTableTemplatesUseResponse201, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, t.client.cfg, "GET", "/v1/projects/"+url.PathEscape(project_id)+"/tables/"+url.PathEscape(table_id), q, nil, nil, "", callHeaders, "GET /v1/projects/{project_id}/tables/{table_id}", nil)
	if err != nil {
		return nil, err
	}
	var out CreateProjectsTableTemplatesUseResponse201
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// List — List tables
func (t *TableResource) List(ctx context.Context, project_id string, opts *TableListOpts) (*ListProjectsTablesResponse200, error) {
	q := url.Values{}
	if opts != nil && opts.Cursor != nil {
		q.Set("cursor", *opts.Cursor)
	}
	if opts != nil && opts.Filter != nil {
		q.Set("filter", *opts.Filter)
	}
	if opts != nil && opts.Lang != nil {
		q.Set("lang", *opts.Lang)
	}
	if opts != nil && opts.Limit != nil {
		q.Set("limit", strconv.FormatInt(*opts.Limit, 10))
	}
	if opts != nil && opts.Order != nil {
		q.Set("order", *opts.Order)
	}
	if opts != nil && opts.Page != nil {
		q.Set("page", strconv.FormatInt(*opts.Page, 10))
	}
	if opts != nil && opts.Q != nil {
		q.Set("q", *opts.Q)
	}
	if opts != nil && opts.Select != nil {
		q.Set("select", *opts.Select)
	}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, t.client.cfg, "GET", "/v1/projects/"+url.PathEscape(project_id)+"/tables", q, nil, nil, "", callHeaders, "GET /v1/projects/{project_id}/tables", nil)
	if err != nil {
		return nil, err
	}
	var out ListProjectsTablesResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Restore — Restore deleted table
func (t *TableResource) Restore(ctx context.Context, project_id string, table_id string, body CreateProjectsTablesRestoreRequest, opts *TableRestoreOpts) (*CreateProjectsTableTemplatesUseResponse201, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, t.client.cfg, "POST", "/v1/projects/"+url.PathEscape(project_id)+"/tables/"+url.PathEscape(table_id)+"/restore", q, body, nil, "", callHeaders, "POST /v1/projects/{project_id}/tables/{table_id}/restore", nil)
	if err != nil {
		return nil, err
	}
	var out CreateProjectsTableTemplatesUseResponse201
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Update — Update table
func (t *TableResource) Update(ctx context.Context, project_id string, table_id string, body UpdateProjectsTableRequest, opts *TableUpdateOpts) (*CreateProjectsTableTemplatesUseResponse201, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, t.client.cfg, "PATCH", "/v1/projects/"+url.PathEscape(project_id)+"/tables/"+url.PathEscape(table_id), q, body, nil, "", callHeaders, "PATCH /v1/projects/{project_id}/tables/{table_id}", nil)
	if err != nil {
		return nil, err
	}
	var out CreateProjectsTableTemplatesUseResponse201
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

type TableTemplateResource struct {
	client *Client
}

func newTableTemplateResource(c *Client) *TableTemplateResource {
	r := &TableTemplateResource{client: c}
	return r
}

// Create — Create table template
func (t *TableTemplateResource) Create(ctx context.Context, body CreateTableTemplateRequest, opts *TableTemplateCreateOpts) (*GetProjectsTableTemplateResponse200, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, t.client.cfg, "POST", "/v1/table-templates", q, body, nil, "", callHeaders, "POST /v1/table-templates", nil)
	if err != nil {
		return nil, err
	}
	var out GetProjectsTableTemplateResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Delete — Delete table template
func (t *TableTemplateResource) Delete(ctx context.Context, template_id string, opts *TableTemplateDeleteOpts) (*DeleteOrganizationsWebhookResponse200, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, t.client.cfg, "DELETE", "/v1/table-templates/"+url.PathEscape(template_id), q, nil, nil, "", callHeaders, "DELETE /v1/table-templates/{template_id}", nil)
	if err != nil {
		return nil, err
	}
	var out DeleteOrganizationsWebhookResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// ListMine — List my table templates
func (t *TableTemplateResource) ListMine(ctx context.Context, opts *TableTemplateListMineOpts) (*ListProjectsTableTemplatesResponse200, error) {
	q := url.Values{}
	if opts != nil && opts.Cursor != nil {
		q.Set("cursor", *opts.Cursor)
	}
	if opts != nil && opts.Filter != nil {
		q.Set("filter", *opts.Filter)
	}
	if opts != nil && opts.Lang != nil {
		q.Set("lang", *opts.Lang)
	}
	if opts != nil && opts.Limit != nil {
		q.Set("limit", strconv.FormatInt(*opts.Limit, 10))
	}
	if opts != nil && opts.Order != nil {
		q.Set("order", *opts.Order)
	}
	if opts != nil && opts.Page != nil {
		q.Set("page", strconv.FormatInt(*opts.Page, 10))
	}
	if opts != nil && opts.Q != nil {
		q.Set("q", *opts.Q)
	}
	if opts != nil && opts.Select != nil {
		q.Set("select", *opts.Select)
	}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, t.client.cfg, "GET", "/v1/table-templates/mine", q, nil, nil, "", callHeaders, "GET /v1/table-templates/mine", nil)
	if err != nil {
		return nil, err
	}
	var out ListProjectsTableTemplatesResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// ProjectGet — Preview table template
func (t *TableTemplateResource) ProjectGet(ctx context.Context, project_id string, template_id string, opts *TableTemplateProjectGetOpts) (*GetProjectsTableTemplateResponse200, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, t.client.cfg, "GET", "/v1/projects/"+url.PathEscape(project_id)+"/table-templates/"+url.PathEscape(template_id), q, nil, nil, "", callHeaders, "GET /v1/projects/{project_id}/table-templates/{template_id}", nil)
	if err != nil {
		return nil, err
	}
	var out GetProjectsTableTemplateResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// ProjectList — Browse table templates
func (t *TableTemplateResource) ProjectList(ctx context.Context, project_id string, opts *TableTemplateProjectListOpts) (*ListProjectsTableTemplatesResponse200, error) {
	q := url.Values{}
	if opts != nil && opts.Cursor != nil {
		q.Set("cursor", *opts.Cursor)
	}
	if opts != nil && opts.Filter != nil {
		q.Set("filter", *opts.Filter)
	}
	if opts != nil && opts.Lang != nil {
		q.Set("lang", *opts.Lang)
	}
	if opts != nil && opts.Limit != nil {
		q.Set("limit", strconv.FormatInt(*opts.Limit, 10))
	}
	if opts != nil && opts.Order != nil {
		q.Set("order", *opts.Order)
	}
	if opts != nil && opts.Page != nil {
		q.Set("page", strconv.FormatInt(*opts.Page, 10))
	}
	if opts != nil && opts.Q != nil {
		q.Set("q", *opts.Q)
	}
	if opts != nil && opts.Select != nil {
		q.Set("select", *opts.Select)
	}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, t.client.cfg, "GET", "/v1/projects/"+url.PathEscape(project_id)+"/table-templates", q, nil, nil, "", callHeaders, "GET /v1/projects/{project_id}/table-templates", nil)
	if err != nil {
		return nil, err
	}
	var out ListProjectsTableTemplatesResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Update — Update table template
func (t *TableTemplateResource) Update(ctx context.Context, template_id string, body UpdateTableTemplateRequest, opts *TableTemplateUpdateOpts) (*GetProjectsTableTemplateResponse200, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, t.client.cfg, "PATCH", "/v1/table-templates/"+url.PathEscape(template_id), q, body, nil, "", callHeaders, "PATCH /v1/table-templates/{template_id}", nil)
	if err != nil {
		return nil, err
	}
	var out GetProjectsTableTemplateResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Use — Create table from template
func (t *TableTemplateResource) Use(ctx context.Context, project_id string, template_id string, body CreateProjectsTableTemplatesUseRequest, opts *TableTemplateUseOpts) (*CreateProjectsTableTemplatesUseResponse201, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, t.client.cfg, "POST", "/v1/projects/"+url.PathEscape(project_id)+"/table-templates/"+url.PathEscape(template_id)+"/use", q, body, nil, "", callHeaders, "POST /v1/projects/{project_id}/table-templates/{template_id}/use", nil)
	if err != nil {
		return nil, err
	}
	var out CreateProjectsTableTemplatesUseResponse201
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

type WebhookResource struct {
	client *Client
}

func newWebhookResource(c *Client) *WebhookResource {
	r := &WebhookResource{client: c}
	return r
}

// Create — Create webhook
func (w *WebhookResource) Create(ctx context.Context, organization_id string, body CreateOrganizationsWebhookRequest, opts *WebhookCreateOpts) (*CreateOrganizationsWebhookResponse201, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, w.client.cfg, "POST", "/v1/organizations/"+url.PathEscape(organization_id)+"/webhooks", q, body, nil, "", callHeaders, "POST /v1/organizations/{organization_id}/webhooks", nil)
	if err != nil {
		return nil, err
	}
	var out CreateOrganizationsWebhookResponse201
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Delete — Delete webhook
func (w *WebhookResource) Delete(ctx context.Context, organization_id string, id string, opts *WebhookDeleteOpts) (*DeleteOrganizationsWebhookResponse200, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, w.client.cfg, "DELETE", "/v1/organizations/"+url.PathEscape(organization_id)+"/webhooks/"+url.PathEscape(id), q, nil, nil, "", callHeaders, "DELETE /v1/organizations/{organization_id}/webhooks/{id}", nil)
	if err != nil {
		return nil, err
	}
	var out DeleteOrganizationsWebhookResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Deliveries — List webhook deliveries
func (w *WebhookResource) Deliveries(ctx context.Context, organization_id string, id string, opts *WebhookDeliveriesOpts) (*ListOrganizationsWebhooksDeliveriesResponse200, error) {
	q := url.Values{}
	if opts != nil && opts.Cursor != nil {
		q.Set("cursor", *opts.Cursor)
	}
	if opts != nil && opts.Event != nil {
		q.Set("event", string(*opts.Event))
	}
	if opts != nil && opts.Filter != nil {
		q.Set("filter", *opts.Filter)
	}
	if opts != nil && opts.Lang != nil {
		q.Set("lang", *opts.Lang)
	}
	if opts != nil && opts.Limit != nil {
		q.Set("limit", strconv.FormatInt(*opts.Limit, 10))
	}
	if opts != nil && opts.Order != nil {
		q.Set("order", *opts.Order)
	}
	if opts != nil && opts.Page != nil {
		q.Set("page", strconv.FormatInt(*opts.Page, 10))
	}
	if opts != nil && opts.Q != nil {
		q.Set("q", *opts.Q)
	}
	if opts != nil && opts.Select != nil {
		q.Set("select", *opts.Select)
	}
	if opts != nil && opts.Status != nil {
		q.Set("status", string(*opts.Status))
	}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, w.client.cfg, "GET", "/v1/organizations/"+url.PathEscape(organization_id)+"/webhooks/"+url.PathEscape(id)+"/deliveries", q, nil, nil, "", callHeaders, "GET /v1/organizations/{organization_id}/webhooks/{id}/deliveries", nil)
	if err != nil {
		return nil, err
	}
	var out ListOrganizationsWebhooksDeliveriesResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Get — Get webhook
func (w *WebhookResource) Get(ctx context.Context, organization_id string, id string, opts *WebhookGetOpts) (*GetOrganizationsWebhookResponse200, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, w.client.cfg, "GET", "/v1/organizations/"+url.PathEscape(organization_id)+"/webhooks/"+url.PathEscape(id), q, nil, nil, "", callHeaders, "GET /v1/organizations/{organization_id}/webhooks/{id}", nil)
	if err != nil {
		return nil, err
	}
	var out GetOrganizationsWebhookResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// List — List webhooks
func (w *WebhookResource) List(ctx context.Context, organization_id string, opts *WebhookListOpts) (*ListOrganizationsWebhooksResponse200, error) {
	q := url.Values{}
	if opts != nil && opts.Cursor != nil {
		q.Set("cursor", *opts.Cursor)
	}
	if opts != nil && opts.Filter != nil {
		q.Set("filter", *opts.Filter)
	}
	if opts != nil && opts.Lang != nil {
		q.Set("lang", *opts.Lang)
	}
	if opts != nil && opts.Limit != nil {
		q.Set("limit", strconv.FormatInt(*opts.Limit, 10))
	}
	if opts != nil && opts.Order != nil {
		q.Set("order", *opts.Order)
	}
	if opts != nil && opts.Page != nil {
		q.Set("page", strconv.FormatInt(*opts.Page, 10))
	}
	if opts != nil && opts.Q != nil {
		q.Set("q", *opts.Q)
	}
	if opts != nil && opts.Select != nil {
		q.Set("select", *opts.Select)
	}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, w.client.cfg, "GET", "/v1/organizations/"+url.PathEscape(organization_id)+"/webhooks", q, nil, nil, "", callHeaders, "GET /v1/organizations/{organization_id}/webhooks", nil)
	if err != nil {
		return nil, err
	}
	var out ListOrganizationsWebhooksResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// RotateSecret — Rotate webhook secret
func (w *WebhookResource) RotateSecret(ctx context.Context, organization_id string, id string, opts *WebhookRotateSecretOpts) (*CreateOrganizationsWebhookResponse201, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, w.client.cfg, "POST", "/v1/organizations/"+url.PathEscape(organization_id)+"/webhooks/"+url.PathEscape(id)+"/rotate-secret", q, nil, nil, "", callHeaders, "POST /v1/organizations/{organization_id}/webhooks/{id}/rotate-secret", nil)
	if err != nil {
		return nil, err
	}
	var out CreateOrganizationsWebhookResponse201
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Test — Send test webhook
func (w *WebhookResource) Test(ctx context.Context, organization_id string, id string, opts *WebhookTestOpts) (*CreateOrganizationsWebhooksTestResponse200, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, w.client.cfg, "POST", "/v1/organizations/"+url.PathEscape(organization_id)+"/webhooks/"+url.PathEscape(id)+"/test", q, nil, nil, "", callHeaders, "POST /v1/organizations/{organization_id}/webhooks/{id}/test", nil)
	if err != nil {
		return nil, err
	}
	var out CreateOrganizationsWebhooksTestResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

// Update — Update webhook
func (w *WebhookResource) Update(ctx context.Context, organization_id string, id string, body UpdateOrganizationsWebhookRequest, opts *WebhookUpdateOpts) (*GetOrganizationsWebhookResponse200, error) {
	q := url.Values{}
	var callHeaders map[string]string
	if opts != nil {
		callHeaders = opts.Headers
	}
	result, err := doRequest(ctx, w.client.cfg, "PATCH", "/v1/organizations/"+url.PathEscape(organization_id)+"/webhooks/"+url.PathEscape(id), q, body, nil, "", callHeaders, "PATCH /v1/organizations/{organization_id}/webhooks/{id}", nil)
	if err != nil {
		return nil, err
	}
	var out GetOrganizationsWebhookResponse200
	if len(result.body) > 0 {
		if err := json.Unmarshal(result.body, &out); err != nil {
			return nil, err
		}
	}
	return &out, nil
}

type BatchDownloadCsvOpts struct {
	Headers map[string]string
}

type BatchDownloadJsonOpts struct {
	Headers map[string]string
}

type BatchDownloadXlsxOpts struct {
	Headers map[string]string
}

type BatchGetOpts struct {
	Headers map[string]string
}

type BatchListOptsStatus string

const (
	BatchListOptsStatusUploading  BatchListOptsStatus = "uploading"
	BatchListOptsStatusProcessing BatchListOptsStatus = "processing"
	BatchListOptsStatusMerging    BatchListOptsStatus = "merging"
	BatchListOptsStatusComplete   BatchListOptsStatus = "complete"
	BatchListOptsStatusPartial    BatchListOptsStatus = "partial"
	BatchListOptsStatusFailed     BatchListOptsStatus = "failed"
)

type BatchListOpts struct {
	Cursor  *string
	Filter  *string
	Lang    *string
	Limit   *int64
	Order   *string
	Page    *int64
	Q       *string
	Select  *string
	Status  *BatchListOptsStatus
	Headers map[string]string
}

type ColumnAddOpts struct {
	Headers map[string]string
}

type ColumnDistinctOpts struct {
	Limit   *int64
	Q       *string
	Headers map[string]string
}

type ColumnRemoveOpts struct {
	Headers map[string]string
}

type ColumnReorderOpts struct {
	Headers map[string]string
}

type ColumnUpdateOpts struct {
	Headers map[string]string
}

type ExportGetOpts struct {
	Headers map[string]string
}

type ExtractOnceOpts struct {
	Headers map[string]string
}

type ExtractStreamOpts struct {
	Headers map[string]string
}

type ExtractTableOnceOpts struct {
	Headers map[string]string
}

type ExtractTableStreamOpts struct {
	Headers map[string]string
}

type RowAggregateOpts struct {
	Aggs    string
	Filter  *string
	Headers map[string]string
}

type RowBulkOpts struct {
	Headers map[string]string
}

type RowCreateOpts struct {
	Headers map[string]string
}

type RowDeleteOpts struct {
	Headers map[string]string
}

type RowGetOpts struct {
	Headers map[string]string
}

type RowListOpts struct {
	Cursor  *string
	Filter  *string
	Limit   *int64
	Order   *string
	Page    *int64
	Q       *string
	Headers map[string]string
}

type RowUpdateOpts struct {
	Headers map[string]string
}

type SuggestSchemaOpts struct {
	Headers map[string]string
}

type TableCreateOpts struct {
	Headers map[string]string
}

type TableDeleteOpts struct {
	Headers map[string]string
}

type TableDuplicateOpts struct {
	Headers map[string]string
}

type TableExportOptsFormat string

const (
	TableExportOptsFormatCsv  TableExportOptsFormat = "csv"
	TableExportOptsFormatJson TableExportOptsFormat = "json"
	TableExportOptsFormatXlsx TableExportOptsFormat = "xlsx"
)

type TableExportOptsSchema string

const (
	TableExportOptsSchemaTrue  TableExportOptsSchema = "true"
	TableExportOptsSchemaFalse TableExportOptsSchema = "false"
)

type TableExportOpts struct {
	Filter  *string
	Format  TableExportOptsFormat
	Order   *string
	Schema  *TableExportOptsSchema
	Search  *string
	Since   *string
	Headers map[string]string
}

type TableGetOpts struct {
	Headers map[string]string
}

type TableListOpts struct {
	Cursor  *string
	Filter  *string
	Lang    *string
	Limit   *int64
	Order   *string
	Page    *int64
	Q       *string
	Select  *string
	Headers map[string]string
}

type TableRestoreOpts struct {
	Headers map[string]string
}

type TableUpdateOpts struct {
	Headers map[string]string
}

type TableTemplateCreateOpts struct {
	Headers map[string]string
}

type TableTemplateDeleteOpts struct {
	Headers map[string]string
}

type TableTemplateListMineOpts struct {
	Cursor  *string
	Filter  *string
	Lang    *string
	Limit   *int64
	Order   *string
	Page    *int64
	Q       *string
	Select  *string
	Headers map[string]string
}

type TableTemplateProjectGetOpts struct {
	Headers map[string]string
}

type TableTemplateProjectListOpts struct {
	Cursor  *string
	Filter  *string
	Lang    *string
	Limit   *int64
	Order   *string
	Page    *int64
	Q       *string
	Select  *string
	Headers map[string]string
}

type TableTemplateUpdateOpts struct {
	Headers map[string]string
}

type TableTemplateUseOpts struct {
	Headers map[string]string
}

type WebhookCreateOpts struct {
	Headers map[string]string
}

type WebhookDeleteOpts struct {
	Headers map[string]string
}

type WebhookDeliveriesOptsEvent string

const (
	WebhookDeliveriesOptsEventBatchComplete WebhookDeliveriesOptsEvent = "batch.complete"
	WebhookDeliveriesOptsEventBatchFailed   WebhookDeliveriesOptsEvent = "batch.failed"
	WebhookDeliveriesOptsEventBatchPartial  WebhookDeliveriesOptsEvent = "batch.partial"
	WebhookDeliveriesOptsEventPing          WebhookDeliveriesOptsEvent = "ping"
)

type WebhookDeliveriesOptsStatus string

const (
	WebhookDeliveriesOptsStatusPending WebhookDeliveriesOptsStatus = "pending"
	WebhookDeliveriesOptsStatusSuccess WebhookDeliveriesOptsStatus = "success"
	WebhookDeliveriesOptsStatusFailed  WebhookDeliveriesOptsStatus = "failed"
)

type WebhookDeliveriesOpts struct {
	Cursor  *string
	Event   *WebhookDeliveriesOptsEvent
	Filter  *string
	Lang    *string
	Limit   *int64
	Order   *string
	Page    *int64
	Q       *string
	Select  *string
	Status  *WebhookDeliveriesOptsStatus
	Headers map[string]string
}

type WebhookGetOpts struct {
	Headers map[string]string
}

type WebhookListOpts struct {
	Cursor  *string
	Filter  *string
	Lang    *string
	Limit   *int64
	Order   *string
	Page    *int64
	Q       *string
	Select  *string
	Headers map[string]string
}

type WebhookRotateSecretOpts struct {
	Headers map[string]string
}

type WebhookTestOpts struct {
	Headers map[string]string
}

type WebhookUpdateOpts struct {
	Headers map[string]string
}
