// Code generated by honey. DO NOT EDIT.
package sdk

import "encoding/json"

type CreateOrganizationsWebhookRequest struct {
	Events []CreateOrganizationsWebhookRequestEvents `json:"events"`
	Name *string `json:"name,omitempty"`
	Url string `json:"url"`
}

type CreateOrganizationsWebhookResponse201 struct {
	Active bool `json:"active"`
	CreatedAt int64 `json:"created_at"`
	EventsJson []CreateOrganizationsWebhookResponse201EventsJson `json:"events_json"`
	FailureCount int64 `json:"failure_count"`
	Id string `json:"id"`
	LastTriggeredAt *int64 `json:"last_triggered_at"`
	Name *string `json:"name"`
	OrganizationId string `json:"organization_id"`
	Secret string `json:"secret"`
	SecretRotatedAt *int64 `json:"secret_rotated_at"`
	UpdatedAt int64 `json:"updated_at"`
	Url string `json:"url"`
}

type CreateOrganizationsWebhooksTestResponse200 struct {
	HttpStatus *float64 `json:"http_status"`
	ResponseBody *string `json:"response_body"`
	Status CreateOrganizationsWebhooksTestResponse200Status `json:"status"`
}

type CreateProjectsExtractResponse200 struct {
	BatchId *string `json:"batch_id,omitempty"`
	Confidence *float64 `json:"confidence"`
	DurationMs *float64 `json:"duration_ms"`
	FailCount float64 `json:"fail_count"`
	Files []struct {
	Confidence *float64 `json:"confidence,omitempty"`
	Error *json.RawMessage `json:"error,omitempty"`
	FileName *json.RawMessage `json:"file_name,omitempty"`
	Rows *float64 `json:"rows,omitempty"`
	Status *string `json:"status,omitempty"`
} `json:"files"`
	Result *CreateProjectsExtractResponse200Result `json:"result,omitempty"`
	Status string `json:"status"`
	SuccessCount float64 `json:"success_count"`
	TotalRows float64 `json:"total_rows"`
}

type CreateProjectsExtractResponse200Result map[string]json.RawMessage

type CreateProjectsSuggestSchemaResponse200 struct {
	Columns []struct {
	Description *string `json:"description,omitempty"`
	Name string `json:"name"`
	Type string `json:"type"`
} `json:"columns"`
	Confidence float64 `json:"confidence"`
	Instruction *string `json:"instruction,omitempty"`
}

type CreateProjectsTableRequest struct {
	ColumnsJson []struct {
	CurrencyCode *string `json:"currency_code,omitempty"`
	Default *json.RawMessage `json:"default,omitempty"`
	Description *string `json:"description,omitempty"`
	Id string `json:"id"`
	Instruction *string `json:"instruction,omitempty"`
	Name string `json:"name"`
	Options []string `json:"options,omitempty"`
	Required *bool `json:"required,omitempty"`
	Searchable *bool `json:"searchable,omitempty"`
	Type *CreateProjectsTableRequestColumnsJsonType `json:"type,omitempty"`
} `json:"columns_json"`
	DefaultSort *string `json:"default_sort,omitempty"`
	InsertMode *CreateProjectsTableRequestInsertMode `json:"insert_mode,omitempty"`
	Instruction *string `json:"instruction,omitempty"`
	MergeColumnsJson []string `json:"merge_columns_json,omitempty"`
	Name string `json:"name"`
	Strictness *CreateProjectsTableRequestStrictness `json:"strictness,omitempty"`
}

type CreateProjectsTablesColumnRequest struct {
	CurrencyCode *string `json:"currency_code,omitempty"`
	Description *string `json:"description,omitempty"`
	Instruction *string `json:"instruction,omitempty"`
	Name string `json:"name"`
	Options []string `json:"options,omitempty"`
	Required *bool `json:"required,omitempty"`
	Type *CreateProjectsTablesColumnRequestType `json:"type,omitempty"`
}

type CreateProjectsTablesDuplicateRequest struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type CreateProjectsTablesRestoreRequest struct {
	Slug *string `json:"slug,omitempty"`
}

type CreateProjectsTablesRowRequest map[string]json.RawMessage

type CreateProjectsTablesRowRequestDbbb57 struct {
	Creates []map[string]json.RawMessage `json:"creates,omitempty"`
	Deletes []string `json:"deletes,omitempty"`
	Updates []struct {
	Data map[string]json.RawMessage `json:"data"`
	Id string `json:"id"`
} `json:"updates,omitempty"`
}

type CreateProjectsTablesRowResponse200 struct {
	Created []map[string]json.RawMessage `json:"created,omitempty"`
	Deleted []string `json:"deleted,omitempty"`
	Updated []map[string]json.RawMessage `json:"updated,omitempty"`
}

type CreateProjectsTableTemplatesUseRequest struct {
	Name string `json:"name"`
	Slug *string `json:"slug,omitempty"`
}

type CreateProjectsTableTemplatesUseResponse201 struct {
	ColumnsJson []struct {
	CurrencyCode *string `json:"currency_code,omitempty"`
	Default *json.RawMessage `json:"default,omitempty"`
	Description *string `json:"description,omitempty"`
	Id string `json:"id"`
	Instruction *string `json:"instruction,omitempty"`
	Name string `json:"name"`
	Options []string `json:"options,omitempty"`
	Required bool `json:"required"`
	Searchable *bool `json:"searchable,omitempty"`
	Type CreateProjectsTableTemplatesUseResponse201ColumnsJsonType `json:"type"`
} `json:"columns_json"`
	CreatedAt int64 `json:"created_at"`
	DataVersion int64 `json:"data_version"`
	DefaultSort *string `json:"default_sort"`
	DeletedAt *int64 `json:"deleted_at"`
	FtsVersion int64 `json:"fts_version"`
	Id string `json:"id"`
	InsertMode CreateProjectsTableTemplatesUseResponse201InsertMode `json:"insert_mode"`
	Instruction *string `json:"instruction"`
	LastUsedAt *int64 `json:"last_used_at"`
	MergeColumnsJson []string `json:"merge_columns_json"`
	Name string `json:"name"`
	ProjectId string `json:"project_id"`
	RowCount int64 `json:"row_count"`
	Slug string `json:"slug"`
	Strictness CreateProjectsTableTemplatesUseResponse201Strictness `json:"strictness"`
	UpdatedAt int64 `json:"updated_at"`
	UsageCount int64 `json:"usage_count"`
}

type CreateTableTemplateRequest struct {
	Category string `json:"category"`
	ColumnsJson []struct {
	CurrencyCode *string `json:"currency_code,omitempty"`
	Default *json.RawMessage `json:"default,omitempty"`
	Description *string `json:"description,omitempty"`
	Id string `json:"id"`
	Instruction *string `json:"instruction,omitempty"`
	Name string `json:"name"`
	Options []string `json:"options,omitempty"`
	Required *bool `json:"required,omitempty"`
	Searchable *bool `json:"searchable,omitempty"`
	Type *CreateTableTemplateRequestColumnsJsonType `json:"type,omitempty"`
} `json:"columns_json"`
	Description *string `json:"description,omitempty"`
	InsertMode *CreateTableTemplateRequestInsertMode `json:"insert_mode,omitempty"`
	Instruction *string `json:"instruction,omitempty"`
	MergeColumnsJson []string `json:"merge_columns_json,omitempty"`
	Name string `json:"name"`
	Strictness *CreateTableTemplateRequestStrictness `json:"strictness,omitempty"`
}

type DeleteOrganizationsWebhookResponse200 struct {
	Id string `json:"id"`
}

type Err400InvalidInput struct {
	ErrorKey Err400InvalidInputErrorKey `json:"error_key"`
	Fields map[string][]struct {
	ErrorKey string `json:"error_key"`
	Message string `json:"message"`
	Path string `json:"path"`
} `json:"fields"`
	Message string `json:"message"`
	Status Err400InvalidInputStatus `json:"status"`
	StatusKey string `json:"status_key"`
	Success bool `json:"success"`
}

type Err401Unauthorized struct {
	ErrorKey Err401UnauthorizedErrorKey `json:"error_key"`
	Fields map[string][]struct {
	ErrorKey string `json:"error_key"`
	Message string `json:"message"`
	Path string `json:"path"`
} `json:"fields"`
	Message string `json:"message"`
	Status Err401UnauthorizedStatus `json:"status"`
	StatusKey string `json:"status_key"`
	Success bool `json:"success"`
}

type Err403EmailNotVerifiedForbidden struct {
	ErrorKey Err403EmailNotVerifiedForbiddenErrorKey `json:"error_key"`
	Fields map[string][]struct {
	ErrorKey string `json:"error_key"`
	Message string `json:"message"`
	Path string `json:"path"`
} `json:"fields"`
	Message string `json:"message"`
	Status Err403EmailNotVerifiedForbiddenStatus `json:"status"`
	StatusKey string `json:"status_key"`
	Success bool `json:"success"`
}

type Err413ContentTooLarge struct {
	ErrorKey Err413ContentTooLargeErrorKey `json:"error_key"`
	Fields map[string][]struct {
	ErrorKey string `json:"error_key"`
	Message string `json:"message"`
	Path string `json:"path"`
} `json:"fields"`
	Message string `json:"message"`
	Status Err413ContentTooLargeStatus `json:"status"`
	StatusKey string `json:"status_key"`
	Success bool `json:"success"`
}

type Err415UnsupportedMediaType struct {
	ErrorKey Err415UnsupportedMediaTypeErrorKey `json:"error_key"`
	Fields map[string][]struct {
	ErrorKey string `json:"error_key"`
	Message string `json:"message"`
	Path string `json:"path"`
} `json:"fields"`
	Message string `json:"message"`
	Status Err415UnsupportedMediaTypeStatus `json:"status"`
	StatusKey string `json:"status_key"`
	Success bool `json:"success"`
}

type Err500InternalServerError struct {
	ErrorKey Err500InternalServerErrorErrorKey `json:"error_key"`
	Fields map[string][]struct {
	ErrorKey string `json:"error_key"`
	Message string `json:"message"`
	Path string `json:"path"`
} `json:"fields"`
	Message string `json:"message"`
	Status Err500InternalServerErrorStatus `json:"status"`
	StatusKey string `json:"status_key"`
	Success bool `json:"success"`
}

type GetOrganizationsWebhookResponse200 struct {
	Active bool `json:"active"`
	CreatedAt int64 `json:"created_at"`
	EventsJson []GetOrganizationsWebhookResponse200EventsJson `json:"events_json"`
	FailureCount int64 `json:"failure_count"`
	Id string `json:"id"`
	LastTriggeredAt *int64 `json:"last_triggered_at"`
	Name *string `json:"name"`
	OrganizationId string `json:"organization_id"`
	SecretRotatedAt *int64 `json:"secret_rotated_at"`
	UpdatedAt int64 `json:"updated_at"`
	Url string `json:"url"`
}

type GetProjectsBatcheResponse200 struct {
	ActorId string `json:"actor_id"`
	ActorType GetProjectsBatcheResponse200ActorType `json:"actor_type"`
	Confidence *float64 `json:"confidence"`
	CreatedAt int64 `json:"created_at"`
	CsvKey *string `json:"csv_key"`
	CurrentFile *string `json:"current_file"`
	DurationMs *int64 `json:"duration_ms"`
	Error *string `json:"error"`
	Extractions []struct {
	BatchId string `json:"batch_id"`
	Confidence *float64 `json:"confidence"`
	CreatedAt int64 `json:"created_at"`
	Error *string `json:"error"`
	FileChecksum *string `json:"file_checksum"`
	FileKey string `json:"file_key"`
	FileName string `json:"file_name"`
	FileType *GetProjectsBatcheResponse200ExtractionsFileType `json:"file_type"`
	Id string `json:"id"`
	RowCount *int64 `json:"row_count"`
	RowsKey *string `json:"rows_key"`
	Status GetProjectsBatcheResponse200ExtractionsStatus `json:"status"`
	TableId *string `json:"table_id"`
} `json:"extractions,omitempty"`
	FileCount int64 `json:"file_count"`
	FilesDone int64 `json:"files_done"`
	Id string `json:"id"`
	InsertMode *GetProjectsBatcheResponse200InsertMode `json:"insert_mode"`
	JsonKey *string `json:"json_key"`
	ProjectId string `json:"project_id"`
	SchemaJson struct {
	Columns []struct {
	Description *string `json:"description,omitempty"`
	Instruction *string `json:"instruction,omitempty"`
	Name string `json:"name"`
	Type GetProjectsBatcheResponse200SchemaJsonColumnsType `json:"type"`
} `json:"columns"`
	Instruction *string `json:"instruction,omitempty"`
	Strictness GetProjectsBatcheResponse200SchemaJsonStrictness `json:"strictness"`
} `json:"schema_json"`
	Status GetProjectsBatcheResponse200Status `json:"status"`
	TableId *string `json:"table_id"`
	TotalRows *int64 `json:"total_rows"`
	UpdatedAt int64 `json:"updated_at"`
	XlsxKey *string `json:"xlsx_key"`
}

type GetProjectsExportResponse200 struct {
	ActorId string `json:"actor_id"`
	Checksum string `json:"checksum"`
	CreatedAt int64 `json:"created_at"`
	CsvKey *string `json:"csv_key"`
	Error *string `json:"error"`
	ExpiresAt *int64 `json:"expires_at"`
	FilterJson *string `json:"filter_json"`
	Id string `json:"id"`
	JsonKey *string `json:"json_key"`
	ProjectId string `json:"project_id"`
	RowCount *int64 `json:"row_count"`
	Status GetProjectsExportResponse200Status `json:"status"`
	TableId *string `json:"table_id"`
	UpdatedAt int64 `json:"updated_at"`
	XlsxKey *string `json:"xlsx_key"`
}

type GetProjectsTableTemplateResponse200 struct {
	Category string `json:"category"`
	ColumnsJson []struct {
	CurrencyCode *string `json:"currency_code,omitempty"`
	Default *json.RawMessage `json:"default,omitempty"`
	Description *string `json:"description,omitempty"`
	Id string `json:"id"`
	Instruction *string `json:"instruction,omitempty"`
	Name string `json:"name"`
	Options []string `json:"options,omitempty"`
	Required bool `json:"required"`
	Searchable *bool `json:"searchable,omitempty"`
	Type GetProjectsTableTemplateResponse200ColumnsJsonType `json:"type"`
} `json:"columns_json"`
	CreatedAt int64 `json:"created_at"`
	CreatorDisplayName *string `json:"creator_display_name"`
	CreatorUserId *string `json:"creator_user_id"`
	Description *string `json:"description"`
	Id string `json:"id"`
	InsertMode GetProjectsTableTemplateResponse200InsertMode `json:"insert_mode"`
	Instruction *string `json:"instruction"`
	MergeColumnsJson []string `json:"merge_columns_json"`
	Name string `json:"name"`
	Strictness GetProjectsTableTemplateResponse200Strictness `json:"strictness"`
	UpdatedAt int64 `json:"updated_at"`
	UsageCount int64 `json:"usage_count"`
}

type ListOrganizationsWebhooksDeliveriesResponse200 struct {
	Count int64 `json:"count"`
	Deliveries []struct {
	Attempt int64 `json:"attempt"`
	CreatedAt int64 `json:"created_at"`
	DeliveredAt *int64 `json:"delivered_at"`
	Event ListOrganizationsWebhooksDeliveriesResponse200DeliveriesEvent `json:"event"`
	HttpStatus *int64 `json:"http_status"`
	Id string `json:"id"`
	NextRetryAt *int64 `json:"next_retry_at"`
	PayloadJson string `json:"payload_json"`
	ResponseBody *string `json:"response_body"`
	Status ListOrganizationsWebhooksDeliveriesResponse200DeliveriesStatus `json:"status"`
	WebhookId string `json:"webhook_id"`
} `json:"deliveries"`
	HasMore bool `json:"hasMore"`
	Limit int64 `json:"limit"`
	NextCursor *string `json:"nextCursor"`
	Page *int64 `json:"page"`
}

type ListOrganizationsWebhooksResponse200 struct {
	Count int64 `json:"count"`
	HasMore bool `json:"hasMore"`
	Limit int64 `json:"limit"`
	NextCursor *string `json:"nextCursor"`
	Page *int64 `json:"page"`
	Webhooks []struct {
	Active bool `json:"active"`
	CreatedAt int64 `json:"created_at"`
	EventsJson []ListOrganizationsWebhooksResponse200WebhooksEventsJson `json:"events_json"`
	FailureCount int64 `json:"failure_count"`
	Id string `json:"id"`
	LastTriggeredAt *int64 `json:"last_triggered_at"`
	Name *string `json:"name"`
	OrganizationId string `json:"organization_id"`
	SecretRotatedAt *int64 `json:"secret_rotated_at"`
	UpdatedAt int64 `json:"updated_at"`
	Url string `json:"url"`
} `json:"webhooks"`
}

type ListProjectsBatchesResponse200 struct {
	Batches []struct {
	ActorId string `json:"actor_id"`
	ActorType ListProjectsBatchesResponse200BatchesActorType `json:"actor_type"`
	Confidence *float64 `json:"confidence"`
	CreatedAt int64 `json:"created_at"`
	CsvKey *string `json:"csv_key"`
	CurrentFile *string `json:"current_file"`
	DurationMs *int64 `json:"duration_ms"`
	Error *string `json:"error"`
	FileCount int64 `json:"file_count"`
	FilesDone int64 `json:"files_done"`
	Id string `json:"id"`
	InsertMode *ListProjectsBatchesResponse200BatchesInsertMode `json:"insert_mode"`
	JsonKey *string `json:"json_key"`
	ProjectId string `json:"project_id"`
	SchemaJson struct {
	Columns []struct {
	Description *string `json:"description,omitempty"`
	Instruction *string `json:"instruction,omitempty"`
	Name string `json:"name"`
	Type ListProjectsBatchesResponse200BatchesSchemaJsonColumnsType `json:"type"`
} `json:"columns"`
	Instruction *string `json:"instruction,omitempty"`
	Strictness ListProjectsBatchesResponse200BatchesSchemaJsonStrictness `json:"strictness"`
} `json:"schema_json"`
	Status ListProjectsBatchesResponse200BatchesStatus `json:"status"`
	TableId *string `json:"table_id"`
	TotalRows *int64 `json:"total_rows"`
	UpdatedAt int64 `json:"updated_at"`
	XlsxKey *string `json:"xlsx_key"`
} `json:"batches"`
	Count int64 `json:"count"`
	HasMore bool `json:"hasMore"`
	Limit int64 `json:"limit"`
	NextCursor *string `json:"nextCursor"`
	Page *int64 `json:"page"`
}

type ListProjectsTablesColumnsDistinctResponse200 struct {
	Values []json.RawMessage `json:"values"`
}

type ListProjectsTablesResponse200 struct {
	Count int64 `json:"count"`
	HasMore bool `json:"hasMore"`
	Limit int64 `json:"limit"`
	NextCursor *string `json:"nextCursor"`
	Page *int64 `json:"page"`
	Tables []struct {
	ColumnsJson []struct {
	CurrencyCode *string `json:"currency_code,omitempty"`
	Default *json.RawMessage `json:"default,omitempty"`
	Description *string `json:"description,omitempty"`
	Id string `json:"id"`
	Instruction *string `json:"instruction,omitempty"`
	Name string `json:"name"`
	Options []string `json:"options,omitempty"`
	Required bool `json:"required"`
	Searchable *bool `json:"searchable,omitempty"`
	Type ListProjectsTablesResponse200TablesColumnsJsonType `json:"type"`
} `json:"columns_json"`
	CreatedAt int64 `json:"created_at"`
	DataVersion int64 `json:"data_version"`
	DefaultSort *string `json:"default_sort"`
	DeletedAt *int64 `json:"deleted_at"`
	FtsVersion int64 `json:"fts_version"`
	Id string `json:"id"`
	InsertMode ListProjectsTablesResponse200TablesInsertMode `json:"insert_mode"`
	Instruction *string `json:"instruction"`
	LastUsedAt *int64 `json:"last_used_at"`
	MergeColumnsJson []string `json:"merge_columns_json"`
	Name string `json:"name"`
	ProjectId string `json:"project_id"`
	RowCount int64 `json:"row_count"`
	Slug string `json:"slug"`
	Strictness ListProjectsTablesResponse200TablesStrictness `json:"strictness"`
	UpdatedAt int64 `json:"updated_at"`
	UsageCount int64 `json:"usage_count"`
} `json:"tables"`
}

type ListProjectsTablesRowsResponse200 struct {
	Count int64 `json:"count"`
	HasMore bool `json:"hasMore"`
	Limit int64 `json:"limit"`
	NextCursor *string `json:"nextCursor"`
	Page *int64 `json:"page"`
	Rows []map[string]json.RawMessage `json:"rows"`
}

type ListProjectsTablesRowsResponse200F7f633 map[string]*float64

type ListProjectsTableTemplatesResponse200 struct {
	Count int64 `json:"count"`
	HasMore bool `json:"hasMore"`
	Limit int64 `json:"limit"`
	NextCursor *string `json:"nextCursor"`
	Page *int64 `json:"page"`
	Templates []struct {
	Category string `json:"category"`
	ColumnsJson []struct {
	CurrencyCode *string `json:"currency_code,omitempty"`
	Default *json.RawMessage `json:"default,omitempty"`
	Description *string `json:"description,omitempty"`
	Id string `json:"id"`
	Instruction *string `json:"instruction,omitempty"`
	Name string `json:"name"`
	Options []string `json:"options,omitempty"`
	Required bool `json:"required"`
	Searchable *bool `json:"searchable,omitempty"`
	Type ListProjectsTableTemplatesResponse200TemplatesColumnsJsonType `json:"type"`
} `json:"columns_json"`
	CreatedAt int64 `json:"created_at"`
	CreatorDisplayName *string `json:"creator_display_name"`
	CreatorUserId *string `json:"creator_user_id"`
	Description *string `json:"description"`
	Id string `json:"id"`
	InsertMode ListProjectsTableTemplatesResponse200TemplatesInsertMode `json:"insert_mode"`
	Instruction *string `json:"instruction"`
	MergeColumnsJson []string `json:"merge_columns_json"`
	Name string `json:"name"`
	Strictness ListProjectsTableTemplatesResponse200TemplatesStrictness `json:"strictness"`
	UpdatedAt int64 `json:"updated_at"`
	UsageCount int64 `json:"usage_count"`
} `json:"templates"`
}

type ReplaceProjectsTablesColumnRequest struct {
	Order []string `json:"order"`
}

type UpdateOrganizationsWebhookRequest struct {
	Active *bool `json:"active,omitempty"`
	Events []UpdateOrganizationsWebhookRequestEvents `json:"events,omitempty"`
	Name *string `json:"name,omitempty"`
	Url *string `json:"url,omitempty"`
}

type UpdateProjectsTableRequest struct {
	DefaultSort *string `json:"default_sort,omitempty"`
	InsertMode *UpdateProjectsTableRequestInsertMode `json:"insert_mode,omitempty"`
	Instruction *string `json:"instruction,omitempty"`
	MergeColumnsJson []string `json:"merge_columns_json,omitempty"`
	Name *string `json:"name,omitempty"`
	Slug *string `json:"slug,omitempty"`
	Strictness *UpdateProjectsTableRequestStrictness `json:"strictness,omitempty"`
}

type UpdateProjectsTablesColumnRequest struct {
	Description *string `json:"description,omitempty"`
	Instruction *string `json:"instruction,omitempty"`
	Name *string `json:"name,omitempty"`
	Options []string `json:"options,omitempty"`
	Required *bool `json:"required,omitempty"`
	Searchable *bool `json:"searchable,omitempty"`
	Type *UpdateProjectsTablesColumnRequestType `json:"type,omitempty"`
}

type UpdateTableTemplateRequest struct {
	Category *string `json:"category,omitempty"`
	ColumnsJson []struct {
	CurrencyCode *string `json:"currency_code,omitempty"`
	Default *json.RawMessage `json:"default,omitempty"`
	Description *string `json:"description,omitempty"`
	Id string `json:"id"`
	Instruction *string `json:"instruction,omitempty"`
	Name string `json:"name"`
	Options []string `json:"options,omitempty"`
	Required *bool `json:"required,omitempty"`
	Searchable *bool `json:"searchable,omitempty"`
	Type *UpdateTableTemplateRequestColumnsJsonType `json:"type,omitempty"`
} `json:"columns_json,omitempty"`
	Description *string `json:"description,omitempty"`
	InsertMode *UpdateTableTemplateRequestInsertMode `json:"insert_mode,omitempty"`
	Instruction *string `json:"instruction,omitempty"`
	MergeColumnsJson []string `json:"merge_columns_json,omitempty"`
	Name *string `json:"name,omitempty"`
	Strictness *UpdateTableTemplateRequestStrictness `json:"strictness,omitempty"`
}

type CreateOrganizationsWebhookRequestEvents string
const (
	CreateOrganizationsWebhookRequestEventsBatchComplete CreateOrganizationsWebhookRequestEvents = "batch.complete"
	CreateOrganizationsWebhookRequestEventsBatchFailed CreateOrganizationsWebhookRequestEvents = "batch.failed"
	CreateOrganizationsWebhookRequestEventsBatchPartial CreateOrganizationsWebhookRequestEvents = "batch.partial"
	CreateOrganizationsWebhookRequestEventsPing CreateOrganizationsWebhookRequestEvents = "ping"
)

type CreateOrganizationsWebhookResponse201EventsJson string
const (
	CreateOrganizationsWebhookResponse201EventsJsonBatchComplete CreateOrganizationsWebhookResponse201EventsJson = "batch.complete"
	CreateOrganizationsWebhookResponse201EventsJsonBatchFailed CreateOrganizationsWebhookResponse201EventsJson = "batch.failed"
	CreateOrganizationsWebhookResponse201EventsJsonBatchPartial CreateOrganizationsWebhookResponse201EventsJson = "batch.partial"
	CreateOrganizationsWebhookResponse201EventsJsonPing CreateOrganizationsWebhookResponse201EventsJson = "ping"
)

type CreateOrganizationsWebhooksTestResponse200Status string
const (
	CreateOrganizationsWebhooksTestResponse200StatusError CreateOrganizationsWebhooksTestResponse200Status = "error"
	CreateOrganizationsWebhooksTestResponse200StatusSuccess CreateOrganizationsWebhooksTestResponse200Status = "success"
	CreateOrganizationsWebhooksTestResponse200StatusTimeout CreateOrganizationsWebhooksTestResponse200Status = "timeout"
)

type CreateProjectsTableRequestColumnsJsonType string
const (
	CreateProjectsTableRequestColumnsJsonTypeArray CreateProjectsTableRequestColumnsJsonType = "array"
	CreateProjectsTableRequestColumnsJsonTypeBoolean CreateProjectsTableRequestColumnsJsonType = "boolean"
	CreateProjectsTableRequestColumnsJsonTypeCurrency CreateProjectsTableRequestColumnsJsonType = "currency"
	CreateProjectsTableRequestColumnsJsonTypeDate CreateProjectsTableRequestColumnsJsonType = "date"
	CreateProjectsTableRequestColumnsJsonTypeEmail CreateProjectsTableRequestColumnsJsonType = "email"
	CreateProjectsTableRequestColumnsJsonTypeEnum CreateProjectsTableRequestColumnsJsonType = "enum"
	CreateProjectsTableRequestColumnsJsonTypeMultiSelect CreateProjectsTableRequestColumnsJsonType = "multi_select"
	CreateProjectsTableRequestColumnsJsonTypeNumber CreateProjectsTableRequestColumnsJsonType = "number"
	CreateProjectsTableRequestColumnsJsonTypeString CreateProjectsTableRequestColumnsJsonType = "string"
	CreateProjectsTableRequestColumnsJsonTypeText CreateProjectsTableRequestColumnsJsonType = "text"
	CreateProjectsTableRequestColumnsJsonTypeUrl CreateProjectsTableRequestColumnsJsonType = "url"
)

type CreateProjectsTableRequestInsertMode string
const (
	CreateProjectsTableRequestInsertModeAppend CreateProjectsTableRequestInsertMode = "append"
	CreateProjectsTableRequestInsertModeDedup CreateProjectsTableRequestInsertMode = "dedup"
	CreateProjectsTableRequestInsertModeMerge CreateProjectsTableRequestInsertMode = "merge"
	CreateProjectsTableRequestInsertModeReplace CreateProjectsTableRequestInsertMode = "replace"
)

type CreateProjectsTableRequestStrictness string
const (
	CreateProjectsTableRequestStrictnessStrict CreateProjectsTableRequestStrictness = "strict"
	CreateProjectsTableRequestStrictnessBalanced CreateProjectsTableRequestStrictness = "balanced"
	CreateProjectsTableRequestStrictnessFlexible CreateProjectsTableRequestStrictness = "flexible"
)

type CreateProjectsTablesColumnRequestType string
const (
	CreateProjectsTablesColumnRequestTypeArray CreateProjectsTablesColumnRequestType = "array"
	CreateProjectsTablesColumnRequestTypeBoolean CreateProjectsTablesColumnRequestType = "boolean"
	CreateProjectsTablesColumnRequestTypeCurrency CreateProjectsTablesColumnRequestType = "currency"
	CreateProjectsTablesColumnRequestTypeDate CreateProjectsTablesColumnRequestType = "date"
	CreateProjectsTablesColumnRequestTypeEmail CreateProjectsTablesColumnRequestType = "email"
	CreateProjectsTablesColumnRequestTypeEnum CreateProjectsTablesColumnRequestType = "enum"
	CreateProjectsTablesColumnRequestTypeMultiSelect CreateProjectsTablesColumnRequestType = "multi_select"
	CreateProjectsTablesColumnRequestTypeNumber CreateProjectsTablesColumnRequestType = "number"
	CreateProjectsTablesColumnRequestTypeString CreateProjectsTablesColumnRequestType = "string"
	CreateProjectsTablesColumnRequestTypeText CreateProjectsTablesColumnRequestType = "text"
	CreateProjectsTablesColumnRequestTypeUrl CreateProjectsTablesColumnRequestType = "url"
)

type CreateProjectsTableTemplatesUseResponse201ColumnsJsonType string
const (
	CreateProjectsTableTemplatesUseResponse201ColumnsJsonTypeArray CreateProjectsTableTemplatesUseResponse201ColumnsJsonType = "array"
	CreateProjectsTableTemplatesUseResponse201ColumnsJsonTypeBoolean CreateProjectsTableTemplatesUseResponse201ColumnsJsonType = "boolean"
	CreateProjectsTableTemplatesUseResponse201ColumnsJsonTypeCurrency CreateProjectsTableTemplatesUseResponse201ColumnsJsonType = "currency"
	CreateProjectsTableTemplatesUseResponse201ColumnsJsonTypeDate CreateProjectsTableTemplatesUseResponse201ColumnsJsonType = "date"
	CreateProjectsTableTemplatesUseResponse201ColumnsJsonTypeEmail CreateProjectsTableTemplatesUseResponse201ColumnsJsonType = "email"
	CreateProjectsTableTemplatesUseResponse201ColumnsJsonTypeEnum CreateProjectsTableTemplatesUseResponse201ColumnsJsonType = "enum"
	CreateProjectsTableTemplatesUseResponse201ColumnsJsonTypeMultiSelect CreateProjectsTableTemplatesUseResponse201ColumnsJsonType = "multi_select"
	CreateProjectsTableTemplatesUseResponse201ColumnsJsonTypeNumber CreateProjectsTableTemplatesUseResponse201ColumnsJsonType = "number"
	CreateProjectsTableTemplatesUseResponse201ColumnsJsonTypeString CreateProjectsTableTemplatesUseResponse201ColumnsJsonType = "string"
	CreateProjectsTableTemplatesUseResponse201ColumnsJsonTypeText CreateProjectsTableTemplatesUseResponse201ColumnsJsonType = "text"
	CreateProjectsTableTemplatesUseResponse201ColumnsJsonTypeUrl CreateProjectsTableTemplatesUseResponse201ColumnsJsonType = "url"
)

type CreateProjectsTableTemplatesUseResponse201InsertMode string
const (
	CreateProjectsTableTemplatesUseResponse201InsertModeAppend CreateProjectsTableTemplatesUseResponse201InsertMode = "append"
	CreateProjectsTableTemplatesUseResponse201InsertModeDedup CreateProjectsTableTemplatesUseResponse201InsertMode = "dedup"
	CreateProjectsTableTemplatesUseResponse201InsertModeMerge CreateProjectsTableTemplatesUseResponse201InsertMode = "merge"
	CreateProjectsTableTemplatesUseResponse201InsertModeReplace CreateProjectsTableTemplatesUseResponse201InsertMode = "replace"
)

type CreateProjectsTableTemplatesUseResponse201Strictness string
const (
	CreateProjectsTableTemplatesUseResponse201StrictnessStrict CreateProjectsTableTemplatesUseResponse201Strictness = "strict"
	CreateProjectsTableTemplatesUseResponse201StrictnessBalanced CreateProjectsTableTemplatesUseResponse201Strictness = "balanced"
	CreateProjectsTableTemplatesUseResponse201StrictnessFlexible CreateProjectsTableTemplatesUseResponse201Strictness = "flexible"
)

type CreateTableTemplateRequestColumnsJsonType string
const (
	CreateTableTemplateRequestColumnsJsonTypeArray CreateTableTemplateRequestColumnsJsonType = "array"
	CreateTableTemplateRequestColumnsJsonTypeBoolean CreateTableTemplateRequestColumnsJsonType = "boolean"
	CreateTableTemplateRequestColumnsJsonTypeCurrency CreateTableTemplateRequestColumnsJsonType = "currency"
	CreateTableTemplateRequestColumnsJsonTypeDate CreateTableTemplateRequestColumnsJsonType = "date"
	CreateTableTemplateRequestColumnsJsonTypeEmail CreateTableTemplateRequestColumnsJsonType = "email"
	CreateTableTemplateRequestColumnsJsonTypeEnum CreateTableTemplateRequestColumnsJsonType = "enum"
	CreateTableTemplateRequestColumnsJsonTypeMultiSelect CreateTableTemplateRequestColumnsJsonType = "multi_select"
	CreateTableTemplateRequestColumnsJsonTypeNumber CreateTableTemplateRequestColumnsJsonType = "number"
	CreateTableTemplateRequestColumnsJsonTypeString CreateTableTemplateRequestColumnsJsonType = "string"
	CreateTableTemplateRequestColumnsJsonTypeText CreateTableTemplateRequestColumnsJsonType = "text"
	CreateTableTemplateRequestColumnsJsonTypeUrl CreateTableTemplateRequestColumnsJsonType = "url"
)

type CreateTableTemplateRequestInsertMode string
const (
	CreateTableTemplateRequestInsertModeAppend CreateTableTemplateRequestInsertMode = "append"
	CreateTableTemplateRequestInsertModeDedup CreateTableTemplateRequestInsertMode = "dedup"
	CreateTableTemplateRequestInsertModeMerge CreateTableTemplateRequestInsertMode = "merge"
	CreateTableTemplateRequestInsertModeReplace CreateTableTemplateRequestInsertMode = "replace"
)

type CreateTableTemplateRequestStrictness string
const (
	CreateTableTemplateRequestStrictnessStrict CreateTableTemplateRequestStrictness = "strict"
	CreateTableTemplateRequestStrictnessBalanced CreateTableTemplateRequestStrictness = "balanced"
	CreateTableTemplateRequestStrictnessFlexible CreateTableTemplateRequestStrictness = "flexible"
)

type Err400InvalidInputErrorKey string
const (
	Err400InvalidInputErrorKeyInvalidInput Err400InvalidInputErrorKey = "invalid_input"
)

type Err400InvalidInputStatus int
const (
	Err400InvalidInputStatus400 Err400InvalidInputStatus = 400
)

type Err401UnauthorizedErrorKey string
const (
	Err401UnauthorizedErrorKeyUnauthorized Err401UnauthorizedErrorKey = "unauthorized"
)

type Err401UnauthorizedStatus int
const (
	Err401UnauthorizedStatus401 Err401UnauthorizedStatus = 401
)

type Err403EmailNotVerifiedForbiddenErrorKey string
const (
	Err403EmailNotVerifiedForbiddenErrorKeyEmailNotVerified Err403EmailNotVerifiedForbiddenErrorKey = "email_not_verified"
	Err403EmailNotVerifiedForbiddenErrorKeyForbidden Err403EmailNotVerifiedForbiddenErrorKey = "forbidden"
)

type Err403EmailNotVerifiedForbiddenStatus int
const (
	Err403EmailNotVerifiedForbiddenStatus403 Err403EmailNotVerifiedForbiddenStatus = 403
)

type Err413ContentTooLargeErrorKey string
const (
	Err413ContentTooLargeErrorKeyContentTooLarge Err413ContentTooLargeErrorKey = "content_too_large"
)

type Err413ContentTooLargeStatus int
const (
	Err413ContentTooLargeStatus413 Err413ContentTooLargeStatus = 413
)

type Err415UnsupportedMediaTypeErrorKey string
const (
	Err415UnsupportedMediaTypeErrorKeyUnsupportedMediaType Err415UnsupportedMediaTypeErrorKey = "unsupported_media_type"
)

type Err415UnsupportedMediaTypeStatus int
const (
	Err415UnsupportedMediaTypeStatus415 Err415UnsupportedMediaTypeStatus = 415
)

type Err500InternalServerErrorErrorKey string
const (
	Err500InternalServerErrorErrorKeyInternalServerError Err500InternalServerErrorErrorKey = "internal_server_error"
)

type Err500InternalServerErrorStatus int
const (
	Err500InternalServerErrorStatus500 Err500InternalServerErrorStatus = 500
)

type GetOrganizationsWebhookResponse200EventsJson string
const (
	GetOrganizationsWebhookResponse200EventsJsonBatchComplete GetOrganizationsWebhookResponse200EventsJson = "batch.complete"
	GetOrganizationsWebhookResponse200EventsJsonBatchFailed GetOrganizationsWebhookResponse200EventsJson = "batch.failed"
	GetOrganizationsWebhookResponse200EventsJsonBatchPartial GetOrganizationsWebhookResponse200EventsJson = "batch.partial"
	GetOrganizationsWebhookResponse200EventsJsonPing GetOrganizationsWebhookResponse200EventsJson = "ping"
)

type GetProjectsBatcheResponse200ActorType string
const (
	GetProjectsBatcheResponse200ActorTypeUser GetProjectsBatcheResponse200ActorType = "user"
	GetProjectsBatcheResponse200ActorTypeApiKey GetProjectsBatcheResponse200ActorType = "api_key"
)

type GetProjectsBatcheResponse200ExtractionsFileType string
const (
	GetProjectsBatcheResponse200ExtractionsFileTypeTextPdf GetProjectsBatcheResponse200ExtractionsFileType = "text_pdf"
	GetProjectsBatcheResponse200ExtractionsFileTypeScanned GetProjectsBatcheResponse200ExtractionsFileType = "scanned"
	GetProjectsBatcheResponse200ExtractionsFileTypeImage GetProjectsBatcheResponse200ExtractionsFileType = "image"
	GetProjectsBatcheResponse200ExtractionsFileTypeText GetProjectsBatcheResponse200ExtractionsFileType = "text"
	GetProjectsBatcheResponse200ExtractionsFileTypeDocument GetProjectsBatcheResponse200ExtractionsFileType = "document"
	GetProjectsBatcheResponse200ExtractionsFileTypeUnknown GetProjectsBatcheResponse200ExtractionsFileType = "unknown"
)

type GetProjectsBatcheResponse200ExtractionsStatus string
const (
	GetProjectsBatcheResponse200ExtractionsStatusPending GetProjectsBatcheResponse200ExtractionsStatus = "pending"
	GetProjectsBatcheResponse200ExtractionsStatusProcessing GetProjectsBatcheResponse200ExtractionsStatus = "processing"
	GetProjectsBatcheResponse200ExtractionsStatusComplete GetProjectsBatcheResponse200ExtractionsStatus = "complete"
	GetProjectsBatcheResponse200ExtractionsStatusFailed GetProjectsBatcheResponse200ExtractionsStatus = "failed"
)

type GetProjectsBatcheResponse200InsertMode string
const (
	GetProjectsBatcheResponse200InsertModeAppend GetProjectsBatcheResponse200InsertMode = "append"
	GetProjectsBatcheResponse200InsertModeDedup GetProjectsBatcheResponse200InsertMode = "dedup"
	GetProjectsBatcheResponse200InsertModeMerge GetProjectsBatcheResponse200InsertMode = "merge"
	GetProjectsBatcheResponse200InsertModeReplace GetProjectsBatcheResponse200InsertMode = "replace"
)

type GetProjectsBatcheResponse200SchemaJsonColumnsType string
const (
	GetProjectsBatcheResponse200SchemaJsonColumnsTypeArray GetProjectsBatcheResponse200SchemaJsonColumnsType = "array"
	GetProjectsBatcheResponse200SchemaJsonColumnsTypeBoolean GetProjectsBatcheResponse200SchemaJsonColumnsType = "boolean"
	GetProjectsBatcheResponse200SchemaJsonColumnsTypeCurrency GetProjectsBatcheResponse200SchemaJsonColumnsType = "currency"
	GetProjectsBatcheResponse200SchemaJsonColumnsTypeDate GetProjectsBatcheResponse200SchemaJsonColumnsType = "date"
	GetProjectsBatcheResponse200SchemaJsonColumnsTypeEmail GetProjectsBatcheResponse200SchemaJsonColumnsType = "email"
	GetProjectsBatcheResponse200SchemaJsonColumnsTypeEnum GetProjectsBatcheResponse200SchemaJsonColumnsType = "enum"
	GetProjectsBatcheResponse200SchemaJsonColumnsTypeMultiSelect GetProjectsBatcheResponse200SchemaJsonColumnsType = "multi_select"
	GetProjectsBatcheResponse200SchemaJsonColumnsTypeNumber GetProjectsBatcheResponse200SchemaJsonColumnsType = "number"
	GetProjectsBatcheResponse200SchemaJsonColumnsTypeString GetProjectsBatcheResponse200SchemaJsonColumnsType = "string"
	GetProjectsBatcheResponse200SchemaJsonColumnsTypeText GetProjectsBatcheResponse200SchemaJsonColumnsType = "text"
	GetProjectsBatcheResponse200SchemaJsonColumnsTypeUrl GetProjectsBatcheResponse200SchemaJsonColumnsType = "url"
)

type GetProjectsBatcheResponse200SchemaJsonStrictness string
const (
	GetProjectsBatcheResponse200SchemaJsonStrictnessStrict GetProjectsBatcheResponse200SchemaJsonStrictness = "strict"
	GetProjectsBatcheResponse200SchemaJsonStrictnessBalanced GetProjectsBatcheResponse200SchemaJsonStrictness = "balanced"
	GetProjectsBatcheResponse200SchemaJsonStrictnessFlexible GetProjectsBatcheResponse200SchemaJsonStrictness = "flexible"
)

type GetProjectsBatcheResponse200Status string
const (
	GetProjectsBatcheResponse200StatusUploading GetProjectsBatcheResponse200Status = "uploading"
	GetProjectsBatcheResponse200StatusProcessing GetProjectsBatcheResponse200Status = "processing"
	GetProjectsBatcheResponse200StatusMerging GetProjectsBatcheResponse200Status = "merging"
	GetProjectsBatcheResponse200StatusComplete GetProjectsBatcheResponse200Status = "complete"
	GetProjectsBatcheResponse200StatusPartial GetProjectsBatcheResponse200Status = "partial"
	GetProjectsBatcheResponse200StatusFailed GetProjectsBatcheResponse200Status = "failed"
)

type GetProjectsExportResponse200Status string
const (
	GetProjectsExportResponse200StatusProcessing GetProjectsExportResponse200Status = "processing"
	GetProjectsExportResponse200StatusComplete GetProjectsExportResponse200Status = "complete"
	GetProjectsExportResponse200StatusFailed GetProjectsExportResponse200Status = "failed"
)

type GetProjectsTableTemplateResponse200ColumnsJsonType string
const (
	GetProjectsTableTemplateResponse200ColumnsJsonTypeArray GetProjectsTableTemplateResponse200ColumnsJsonType = "array"
	GetProjectsTableTemplateResponse200ColumnsJsonTypeBoolean GetProjectsTableTemplateResponse200ColumnsJsonType = "boolean"
	GetProjectsTableTemplateResponse200ColumnsJsonTypeCurrency GetProjectsTableTemplateResponse200ColumnsJsonType = "currency"
	GetProjectsTableTemplateResponse200ColumnsJsonTypeDate GetProjectsTableTemplateResponse200ColumnsJsonType = "date"
	GetProjectsTableTemplateResponse200ColumnsJsonTypeEmail GetProjectsTableTemplateResponse200ColumnsJsonType = "email"
	GetProjectsTableTemplateResponse200ColumnsJsonTypeEnum GetProjectsTableTemplateResponse200ColumnsJsonType = "enum"
	GetProjectsTableTemplateResponse200ColumnsJsonTypeMultiSelect GetProjectsTableTemplateResponse200ColumnsJsonType = "multi_select"
	GetProjectsTableTemplateResponse200ColumnsJsonTypeNumber GetProjectsTableTemplateResponse200ColumnsJsonType = "number"
	GetProjectsTableTemplateResponse200ColumnsJsonTypeString GetProjectsTableTemplateResponse200ColumnsJsonType = "string"
	GetProjectsTableTemplateResponse200ColumnsJsonTypeText GetProjectsTableTemplateResponse200ColumnsJsonType = "text"
	GetProjectsTableTemplateResponse200ColumnsJsonTypeUrl GetProjectsTableTemplateResponse200ColumnsJsonType = "url"
)

type GetProjectsTableTemplateResponse200InsertMode string
const (
	GetProjectsTableTemplateResponse200InsertModeAppend GetProjectsTableTemplateResponse200InsertMode = "append"
	GetProjectsTableTemplateResponse200InsertModeDedup GetProjectsTableTemplateResponse200InsertMode = "dedup"
	GetProjectsTableTemplateResponse200InsertModeMerge GetProjectsTableTemplateResponse200InsertMode = "merge"
	GetProjectsTableTemplateResponse200InsertModeReplace GetProjectsTableTemplateResponse200InsertMode = "replace"
)

type GetProjectsTableTemplateResponse200Strictness string
const (
	GetProjectsTableTemplateResponse200StrictnessStrict GetProjectsTableTemplateResponse200Strictness = "strict"
	GetProjectsTableTemplateResponse200StrictnessBalanced GetProjectsTableTemplateResponse200Strictness = "balanced"
	GetProjectsTableTemplateResponse200StrictnessFlexible GetProjectsTableTemplateResponse200Strictness = "flexible"
)

type ListOrganizationsWebhooksDeliveriesResponse200DeliveriesEvent string
const (
	ListOrganizationsWebhooksDeliveriesResponse200DeliveriesEventBatchComplete ListOrganizationsWebhooksDeliveriesResponse200DeliveriesEvent = "batch.complete"
	ListOrganizationsWebhooksDeliveriesResponse200DeliveriesEventBatchFailed ListOrganizationsWebhooksDeliveriesResponse200DeliveriesEvent = "batch.failed"
	ListOrganizationsWebhooksDeliveriesResponse200DeliveriesEventBatchPartial ListOrganizationsWebhooksDeliveriesResponse200DeliveriesEvent = "batch.partial"
	ListOrganizationsWebhooksDeliveriesResponse200DeliveriesEventPing ListOrganizationsWebhooksDeliveriesResponse200DeliveriesEvent = "ping"
)

type ListOrganizationsWebhooksDeliveriesResponse200DeliveriesStatus string
const (
	ListOrganizationsWebhooksDeliveriesResponse200DeliveriesStatusPending ListOrganizationsWebhooksDeliveriesResponse200DeliveriesStatus = "pending"
	ListOrganizationsWebhooksDeliveriesResponse200DeliveriesStatusSuccess ListOrganizationsWebhooksDeliveriesResponse200DeliveriesStatus = "success"
	ListOrganizationsWebhooksDeliveriesResponse200DeliveriesStatusFailed ListOrganizationsWebhooksDeliveriesResponse200DeliveriesStatus = "failed"
)

type ListOrganizationsWebhooksResponse200WebhooksEventsJson string
const (
	ListOrganizationsWebhooksResponse200WebhooksEventsJsonBatchComplete ListOrganizationsWebhooksResponse200WebhooksEventsJson = "batch.complete"
	ListOrganizationsWebhooksResponse200WebhooksEventsJsonBatchFailed ListOrganizationsWebhooksResponse200WebhooksEventsJson = "batch.failed"
	ListOrganizationsWebhooksResponse200WebhooksEventsJsonBatchPartial ListOrganizationsWebhooksResponse200WebhooksEventsJson = "batch.partial"
	ListOrganizationsWebhooksResponse200WebhooksEventsJsonPing ListOrganizationsWebhooksResponse200WebhooksEventsJson = "ping"
)

type ListProjectsBatchesResponse200BatchesActorType string
const (
	ListProjectsBatchesResponse200BatchesActorTypeUser ListProjectsBatchesResponse200BatchesActorType = "user"
	ListProjectsBatchesResponse200BatchesActorTypeApiKey ListProjectsBatchesResponse200BatchesActorType = "api_key"
)

type ListProjectsBatchesResponse200BatchesInsertMode string
const (
	ListProjectsBatchesResponse200BatchesInsertModeAppend ListProjectsBatchesResponse200BatchesInsertMode = "append"
	ListProjectsBatchesResponse200BatchesInsertModeDedup ListProjectsBatchesResponse200BatchesInsertMode = "dedup"
	ListProjectsBatchesResponse200BatchesInsertModeMerge ListProjectsBatchesResponse200BatchesInsertMode = "merge"
	ListProjectsBatchesResponse200BatchesInsertModeReplace ListProjectsBatchesResponse200BatchesInsertMode = "replace"
)

type ListProjectsBatchesResponse200BatchesSchemaJsonColumnsType string
const (
	ListProjectsBatchesResponse200BatchesSchemaJsonColumnsTypeArray ListProjectsBatchesResponse200BatchesSchemaJsonColumnsType = "array"
	ListProjectsBatchesResponse200BatchesSchemaJsonColumnsTypeBoolean ListProjectsBatchesResponse200BatchesSchemaJsonColumnsType = "boolean"
	ListProjectsBatchesResponse200BatchesSchemaJsonColumnsTypeCurrency ListProjectsBatchesResponse200BatchesSchemaJsonColumnsType = "currency"
	ListProjectsBatchesResponse200BatchesSchemaJsonColumnsTypeDate ListProjectsBatchesResponse200BatchesSchemaJsonColumnsType = "date"
	ListProjectsBatchesResponse200BatchesSchemaJsonColumnsTypeEmail ListProjectsBatchesResponse200BatchesSchemaJsonColumnsType = "email"
	ListProjectsBatchesResponse200BatchesSchemaJsonColumnsTypeEnum ListProjectsBatchesResponse200BatchesSchemaJsonColumnsType = "enum"
	ListProjectsBatchesResponse200BatchesSchemaJsonColumnsTypeMultiSelect ListProjectsBatchesResponse200BatchesSchemaJsonColumnsType = "multi_select"
	ListProjectsBatchesResponse200BatchesSchemaJsonColumnsTypeNumber ListProjectsBatchesResponse200BatchesSchemaJsonColumnsType = "number"
	ListProjectsBatchesResponse200BatchesSchemaJsonColumnsTypeString ListProjectsBatchesResponse200BatchesSchemaJsonColumnsType = "string"
	ListProjectsBatchesResponse200BatchesSchemaJsonColumnsTypeText ListProjectsBatchesResponse200BatchesSchemaJsonColumnsType = "text"
	ListProjectsBatchesResponse200BatchesSchemaJsonColumnsTypeUrl ListProjectsBatchesResponse200BatchesSchemaJsonColumnsType = "url"
)

type ListProjectsBatchesResponse200BatchesSchemaJsonStrictness string
const (
	ListProjectsBatchesResponse200BatchesSchemaJsonStrictnessStrict ListProjectsBatchesResponse200BatchesSchemaJsonStrictness = "strict"
	ListProjectsBatchesResponse200BatchesSchemaJsonStrictnessBalanced ListProjectsBatchesResponse200BatchesSchemaJsonStrictness = "balanced"
	ListProjectsBatchesResponse200BatchesSchemaJsonStrictnessFlexible ListProjectsBatchesResponse200BatchesSchemaJsonStrictness = "flexible"
)

type ListProjectsBatchesResponse200BatchesStatus string
const (
	ListProjectsBatchesResponse200BatchesStatusUploading ListProjectsBatchesResponse200BatchesStatus = "uploading"
	ListProjectsBatchesResponse200BatchesStatusProcessing ListProjectsBatchesResponse200BatchesStatus = "processing"
	ListProjectsBatchesResponse200BatchesStatusMerging ListProjectsBatchesResponse200BatchesStatus = "merging"
	ListProjectsBatchesResponse200BatchesStatusComplete ListProjectsBatchesResponse200BatchesStatus = "complete"
	ListProjectsBatchesResponse200BatchesStatusPartial ListProjectsBatchesResponse200BatchesStatus = "partial"
	ListProjectsBatchesResponse200BatchesStatusFailed ListProjectsBatchesResponse200BatchesStatus = "failed"
)

type ListProjectsTablesResponse200TablesColumnsJsonType string
const (
	ListProjectsTablesResponse200TablesColumnsJsonTypeArray ListProjectsTablesResponse200TablesColumnsJsonType = "array"
	ListProjectsTablesResponse200TablesColumnsJsonTypeBoolean ListProjectsTablesResponse200TablesColumnsJsonType = "boolean"
	ListProjectsTablesResponse200TablesColumnsJsonTypeCurrency ListProjectsTablesResponse200TablesColumnsJsonType = "currency"
	ListProjectsTablesResponse200TablesColumnsJsonTypeDate ListProjectsTablesResponse200TablesColumnsJsonType = "date"
	ListProjectsTablesResponse200TablesColumnsJsonTypeEmail ListProjectsTablesResponse200TablesColumnsJsonType = "email"
	ListProjectsTablesResponse200TablesColumnsJsonTypeEnum ListProjectsTablesResponse200TablesColumnsJsonType = "enum"
	ListProjectsTablesResponse200TablesColumnsJsonTypeMultiSelect ListProjectsTablesResponse200TablesColumnsJsonType = "multi_select"
	ListProjectsTablesResponse200TablesColumnsJsonTypeNumber ListProjectsTablesResponse200TablesColumnsJsonType = "number"
	ListProjectsTablesResponse200TablesColumnsJsonTypeString ListProjectsTablesResponse200TablesColumnsJsonType = "string"
	ListProjectsTablesResponse200TablesColumnsJsonTypeText ListProjectsTablesResponse200TablesColumnsJsonType = "text"
	ListProjectsTablesResponse200TablesColumnsJsonTypeUrl ListProjectsTablesResponse200TablesColumnsJsonType = "url"
)

type ListProjectsTablesResponse200TablesInsertMode string
const (
	ListProjectsTablesResponse200TablesInsertModeAppend ListProjectsTablesResponse200TablesInsertMode = "append"
	ListProjectsTablesResponse200TablesInsertModeDedup ListProjectsTablesResponse200TablesInsertMode = "dedup"
	ListProjectsTablesResponse200TablesInsertModeMerge ListProjectsTablesResponse200TablesInsertMode = "merge"
	ListProjectsTablesResponse200TablesInsertModeReplace ListProjectsTablesResponse200TablesInsertMode = "replace"
)

type ListProjectsTablesResponse200TablesStrictness string
const (
	ListProjectsTablesResponse200TablesStrictnessStrict ListProjectsTablesResponse200TablesStrictness = "strict"
	ListProjectsTablesResponse200TablesStrictnessBalanced ListProjectsTablesResponse200TablesStrictness = "balanced"
	ListProjectsTablesResponse200TablesStrictnessFlexible ListProjectsTablesResponse200TablesStrictness = "flexible"
)

type ListProjectsTableTemplatesResponse200TemplatesColumnsJsonType string
const (
	ListProjectsTableTemplatesResponse200TemplatesColumnsJsonTypeArray ListProjectsTableTemplatesResponse200TemplatesColumnsJsonType = "array"
	ListProjectsTableTemplatesResponse200TemplatesColumnsJsonTypeBoolean ListProjectsTableTemplatesResponse200TemplatesColumnsJsonType = "boolean"
	ListProjectsTableTemplatesResponse200TemplatesColumnsJsonTypeCurrency ListProjectsTableTemplatesResponse200TemplatesColumnsJsonType = "currency"
	ListProjectsTableTemplatesResponse200TemplatesColumnsJsonTypeDate ListProjectsTableTemplatesResponse200TemplatesColumnsJsonType = "date"
	ListProjectsTableTemplatesResponse200TemplatesColumnsJsonTypeEmail ListProjectsTableTemplatesResponse200TemplatesColumnsJsonType = "email"
	ListProjectsTableTemplatesResponse200TemplatesColumnsJsonTypeEnum ListProjectsTableTemplatesResponse200TemplatesColumnsJsonType = "enum"
	ListProjectsTableTemplatesResponse200TemplatesColumnsJsonTypeMultiSelect ListProjectsTableTemplatesResponse200TemplatesColumnsJsonType = "multi_select"
	ListProjectsTableTemplatesResponse200TemplatesColumnsJsonTypeNumber ListProjectsTableTemplatesResponse200TemplatesColumnsJsonType = "number"
	ListProjectsTableTemplatesResponse200TemplatesColumnsJsonTypeString ListProjectsTableTemplatesResponse200TemplatesColumnsJsonType = "string"
	ListProjectsTableTemplatesResponse200TemplatesColumnsJsonTypeText ListProjectsTableTemplatesResponse200TemplatesColumnsJsonType = "text"
	ListProjectsTableTemplatesResponse200TemplatesColumnsJsonTypeUrl ListProjectsTableTemplatesResponse200TemplatesColumnsJsonType = "url"
)

type ListProjectsTableTemplatesResponse200TemplatesInsertMode string
const (
	ListProjectsTableTemplatesResponse200TemplatesInsertModeAppend ListProjectsTableTemplatesResponse200TemplatesInsertMode = "append"
	ListProjectsTableTemplatesResponse200TemplatesInsertModeDedup ListProjectsTableTemplatesResponse200TemplatesInsertMode = "dedup"
	ListProjectsTableTemplatesResponse200TemplatesInsertModeMerge ListProjectsTableTemplatesResponse200TemplatesInsertMode = "merge"
	ListProjectsTableTemplatesResponse200TemplatesInsertModeReplace ListProjectsTableTemplatesResponse200TemplatesInsertMode = "replace"
)

type ListProjectsTableTemplatesResponse200TemplatesStrictness string
const (
	ListProjectsTableTemplatesResponse200TemplatesStrictnessStrict ListProjectsTableTemplatesResponse200TemplatesStrictness = "strict"
	ListProjectsTableTemplatesResponse200TemplatesStrictnessBalanced ListProjectsTableTemplatesResponse200TemplatesStrictness = "balanced"
	ListProjectsTableTemplatesResponse200TemplatesStrictnessFlexible ListProjectsTableTemplatesResponse200TemplatesStrictness = "flexible"
)

type UpdateOrganizationsWebhookRequestEvents string
const (
	UpdateOrganizationsWebhookRequestEventsBatchComplete UpdateOrganizationsWebhookRequestEvents = "batch.complete"
	UpdateOrganizationsWebhookRequestEventsBatchFailed UpdateOrganizationsWebhookRequestEvents = "batch.failed"
	UpdateOrganizationsWebhookRequestEventsBatchPartial UpdateOrganizationsWebhookRequestEvents = "batch.partial"
	UpdateOrganizationsWebhookRequestEventsPing UpdateOrganizationsWebhookRequestEvents = "ping"
)

type UpdateProjectsTableRequestInsertMode string
const (
	UpdateProjectsTableRequestInsertModeAppend UpdateProjectsTableRequestInsertMode = "append"
	UpdateProjectsTableRequestInsertModeDedup UpdateProjectsTableRequestInsertMode = "dedup"
	UpdateProjectsTableRequestInsertModeMerge UpdateProjectsTableRequestInsertMode = "merge"
	UpdateProjectsTableRequestInsertModeReplace UpdateProjectsTableRequestInsertMode = "replace"
)

type UpdateProjectsTableRequestStrictness string
const (
	UpdateProjectsTableRequestStrictnessStrict UpdateProjectsTableRequestStrictness = "strict"
	UpdateProjectsTableRequestStrictnessBalanced UpdateProjectsTableRequestStrictness = "balanced"
	UpdateProjectsTableRequestStrictnessFlexible UpdateProjectsTableRequestStrictness = "flexible"
)

type UpdateProjectsTablesColumnRequestType string
const (
	UpdateProjectsTablesColumnRequestTypeArray UpdateProjectsTablesColumnRequestType = "array"
	UpdateProjectsTablesColumnRequestTypeBoolean UpdateProjectsTablesColumnRequestType = "boolean"
	UpdateProjectsTablesColumnRequestTypeCurrency UpdateProjectsTablesColumnRequestType = "currency"
	UpdateProjectsTablesColumnRequestTypeDate UpdateProjectsTablesColumnRequestType = "date"
	UpdateProjectsTablesColumnRequestTypeEmail UpdateProjectsTablesColumnRequestType = "email"
	UpdateProjectsTablesColumnRequestTypeEnum UpdateProjectsTablesColumnRequestType = "enum"
	UpdateProjectsTablesColumnRequestTypeMultiSelect UpdateProjectsTablesColumnRequestType = "multi_select"
	UpdateProjectsTablesColumnRequestTypeNumber UpdateProjectsTablesColumnRequestType = "number"
	UpdateProjectsTablesColumnRequestTypeString UpdateProjectsTablesColumnRequestType = "string"
	UpdateProjectsTablesColumnRequestTypeText UpdateProjectsTablesColumnRequestType = "text"
	UpdateProjectsTablesColumnRequestTypeUrl UpdateProjectsTablesColumnRequestType = "url"
)

type UpdateTableTemplateRequestColumnsJsonType string
const (
	UpdateTableTemplateRequestColumnsJsonTypeArray UpdateTableTemplateRequestColumnsJsonType = "array"
	UpdateTableTemplateRequestColumnsJsonTypeBoolean UpdateTableTemplateRequestColumnsJsonType = "boolean"
	UpdateTableTemplateRequestColumnsJsonTypeCurrency UpdateTableTemplateRequestColumnsJsonType = "currency"
	UpdateTableTemplateRequestColumnsJsonTypeDate UpdateTableTemplateRequestColumnsJsonType = "date"
	UpdateTableTemplateRequestColumnsJsonTypeEmail UpdateTableTemplateRequestColumnsJsonType = "email"
	UpdateTableTemplateRequestColumnsJsonTypeEnum UpdateTableTemplateRequestColumnsJsonType = "enum"
	UpdateTableTemplateRequestColumnsJsonTypeMultiSelect UpdateTableTemplateRequestColumnsJsonType = "multi_select"
	UpdateTableTemplateRequestColumnsJsonTypeNumber UpdateTableTemplateRequestColumnsJsonType = "number"
	UpdateTableTemplateRequestColumnsJsonTypeString UpdateTableTemplateRequestColumnsJsonType = "string"
	UpdateTableTemplateRequestColumnsJsonTypeText UpdateTableTemplateRequestColumnsJsonType = "text"
	UpdateTableTemplateRequestColumnsJsonTypeUrl UpdateTableTemplateRequestColumnsJsonType = "url"
)

type UpdateTableTemplateRequestInsertMode string
const (
	UpdateTableTemplateRequestInsertModeAppend UpdateTableTemplateRequestInsertMode = "append"
	UpdateTableTemplateRequestInsertModeDedup UpdateTableTemplateRequestInsertMode = "dedup"
	UpdateTableTemplateRequestInsertModeMerge UpdateTableTemplateRequestInsertMode = "merge"
	UpdateTableTemplateRequestInsertModeReplace UpdateTableTemplateRequestInsertMode = "replace"
)

type UpdateTableTemplateRequestStrictness string
const (
	UpdateTableTemplateRequestStrictnessStrict UpdateTableTemplateRequestStrictness = "strict"
	UpdateTableTemplateRequestStrictnessBalanced UpdateTableTemplateRequestStrictness = "balanced"
	UpdateTableTemplateRequestStrictnessFlexible UpdateTableTemplateRequestStrictness = "flexible"
)
